version: 2
project_name: deltascope

builds:
  - id: deltascope-linux-arm64-pg
    binary: deltascope
    main: ./cmd/deltascope
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X github.com/Fanduzi/DeltaScope/internal/interfaces/cli.Version={{ .Tag }}
    flags:
      - -tags=postgresql
      - -buildvcs=false
    goos:
      - linux
    goarch:
      - arm64
  - id: deltascope-server-linux-arm64-pg
    binary: deltascope-server
    main: ./cmd/deltascope-server
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X main.Version={{ .Tag }}
    flags:
      - -tags=postgresql
      - -buildvcs=false
    goos:
      - linux
    goarch:
      - arm64
  - id: deltascope-mcp-linux-arm64-pg
    binary: deltascope-mcp
    main: ./cmd/deltascope-mcp
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X main.Version={{ .Tag }}
    flags:
      - -tags=postgresql
      - -buildvcs=false
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: default-linux-arm64-pg
    ids:
      - deltascope-linux-arm64-pg
      - deltascope-server-linux-arm64-pg
      - deltascope-mcp-linux-arm64-pg
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .RawVersion }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - README_ZH.md
      - CHANGELOG.md
      - SECURITY.md

checksum:
  name_template: "deltascope_{{ .RawVersion }}_checksums.txt"
