//go:build postgresql

package audit

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
)

type alterTableCensusStatus string

const (
	alterTableStatusFindingCovered   alterTableCensusStatus = "finding-covered"
	alterTableStatusNormalizedSilent alterTableCensusStatus = "normalized-silent-pass"
	alterTableStatusUnsupportedExp   alterTableCensusStatus = "unsupported-explicit"
	alterTableStatusParserError      alterTableCensusStatus = "parser-error"
	alterTableStatusUnclassified     alterTableCensusStatus = "unclassified"
)

type alterTableCensusResult struct {
	Name            string
	ParseOK         bool
	Kind            string
	Unsupported     bool
	UnsupportedFeat string
	UnsupportedWhy  string
	Normalized      bool
	DDLOperation    string
	AlterActions    []string
	FindingRuleIDs  []string
	Status          alterTableCensusStatus
}

var pgAlterTableCensusCases = []struct {
	Name string
	SQL  string
}{
	{Name: "DROP COLUMN", SQL: "ALTER TABLE users DROP COLUMN email"},
	{Name: "DROP COLUMN IF EXISTS", SQL: "ALTER TABLE users DROP COLUMN IF EXISTS email"},
	{Name: "DROP COLUMN CASCADE", SQL: "ALTER TABLE users DROP COLUMN email CASCADE"},
	{Name: "RENAME COLUMN", SQL: "ALTER TABLE users RENAME COLUMN email TO mail"},
	{Name: "RENAME TABLE", SQL: "ALTER TABLE users RENAME TO accounts"},
	{Name: "ADD COLUMN NOT NULL DEFAULT", SQL: "ALTER TABLE users ADD COLUMN email text NOT NULL DEFAULT ''"},
	{Name: "ADD COLUMN NOT NULL NO DEFAULT", SQL: "ALTER TABLE users ADD COLUMN bio text NOT NULL"},
	{Name: "ADD COLUMN NULLABLE", SQL: "ALTER TABLE users ADD COLUMN bio text"},
	{Name: "ALTER COLUMN TYPE", SQL: "ALTER TABLE users ALTER COLUMN name TYPE text"},
	{Name: "ALTER COLUMN TYPE USING", SQL: "ALTER TABLE users ALTER COLUMN name TYPE jsonb USING to_jsonb(name)"},
	{Name: "SET DEFAULT", SQL: "ALTER TABLE users ALTER COLUMN name SET DEFAULT 'unknown'"},
	{Name: "DROP DEFAULT", SQL: "ALTER TABLE users ALTER COLUMN name DROP DEFAULT"},
	{Name: "SET NOT NULL", SQL: "ALTER TABLE users ALTER COLUMN name SET NOT NULL"},
	{Name: "DROP NOT NULL", SQL: "ALTER TABLE users ALTER COLUMN name DROP NOT NULL"},
	{Name: "ADD PRIMARY KEY", SQL: "ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id)"},
	{Name: "ADD UNIQUE", SQL: "ALTER TABLE users ADD CONSTRAINT uniq_email UNIQUE (email)"},
	{Name: "ADD FOREIGN KEY", SQL: "ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)"},
	{Name: "ADD CHECK", SQL: "ALTER TABLE products ADD CONSTRAINT chk_price CHECK (price > 0)"},
	{Name: "ADD CHECK NOT VALID", SQL: "ALTER TABLE products ADD CONSTRAINT chk_price CHECK (price > 0) NOT VALID"},
	{Name: "DROP CONSTRAINT", SQL: "ALTER TABLE users DROP CONSTRAINT uniq_email"},
	{Name: "DROP CONSTRAINT CASCADE", SQL: "ALTER TABLE users DROP CONSTRAINT uniq_email CASCADE"},
	{Name: "VALIDATE CONSTRAINT", SQL: "ALTER TABLE users VALIDATE CONSTRAINT chk_price"},
	{Name: "DROP EXPRESSION", SQL: "ALTER TABLE t ALTER COLUMN b DROP EXPRESSION"},
	{Name: "SET GENERATED", SQL: "ALTER TABLE t ALTER COLUMN id SET GENERATED BY DEFAULT"},
	{Name: "DROP IDENTITY", SQL: "ALTER TABLE t ALTER COLUMN id DROP IDENTITY"},
	{Name: "SET SCHEMA", SQL: "ALTER TABLE users SET SCHEMA archive"},
	{Name: "OWNER TO", SQL: "ALTER TABLE users OWNER TO app_owner"},
	{Name: "ENABLE TRIGGER", SQL: "ALTER TABLE users ENABLE TRIGGER trg_users_audit"},
	{Name: "DISABLE TRIGGER", SQL: "ALTER TABLE users DISABLE TRIGGER trg_users_audit"},
	{Name: "ENABLE TRIGGER ALL", SQL: "ALTER TABLE users ENABLE TRIGGER ALL"},
	{Name: "ENABLE TRIGGER USER", SQL: "ALTER TABLE users ENABLE TRIGGER USER"},
	{Name: "DISABLE TRIGGER ALL", SQL: "ALTER TABLE users DISABLE TRIGGER ALL"},
	{Name: "DISABLE TRIGGER USER", SQL: "ALTER TABLE users DISABLE TRIGGER USER"},
	{Name: "REPLICA IDENTITY DEFAULT", SQL: "ALTER TABLE users REPLICA IDENTITY DEFAULT"},
	{Name: "REPLICA IDENTITY FULL", SQL: "ALTER TABLE users REPLICA IDENTITY FULL"},
	{Name: "REPLICA IDENTITY NOTHING", SQL: "ALTER TABLE users REPLICA IDENTITY NOTHING"},
	{Name: "REPLICA IDENTITY USING INDEX", SQL: "ALTER TABLE users REPLICA IDENTITY USING INDEX users_replica_identity_idx"},
	{Name: "ATTACH PARTITION", SQL: "ALTER TABLE measurement ATTACH PARTITION measurement_y2026m04 FOR VALUES FROM ('2026-04-01') TO ('2026-05-01')"},
	{Name: "DETACH PARTITION", SQL: "ALTER TABLE measurement DETACH PARTITION measurement_y2026m04"},
	{Name: "SET LOGGED", SQL: "ALTER TABLE users SET LOGGED"},
	{Name: "SET UNLOGGED", SQL: "ALTER TABLE users SET UNLOGGED"},
	{Name: "SET TABLESPACE", SQL: "ALTER TABLE users SET TABLESPACE fastspace"},
}

func TestPostgreSQLAlterTableCoverageCensus(t *testing.T) {
	t.Parallel()
	var results []alterTableCensusResult

	for _, tc := range pgAlterTableCensusCases {
		res := classifyAlterTableCensusResult(t, tc.Name, tc.SQL)
		results = append(results, res)
	}

	logAlterTableCensusTable(t, results)

	var parseable, parserErrors, unsupported, normalized, findingCovered, silentPass, unclassified int
	for _, r := range results {
		switch r.Status {
		case alterTableStatusParserError:
			parserErrors++
		case alterTableStatusUnsupportedExp:
			unsupported++
		case alterTableStatusFindingCovered:
			findingCovered++
			normalized++
			parseable++
		case alterTableStatusNormalizedSilent:
			silentPass++
			normalized++
			parseable++
		case alterTableStatusUnclassified:
			unclassified++
			parseable++
		}
	}

	t.Log("")
	t.Log("=== ALTER TABLE Census Summary ===")
	t.Logf("Total forms:                %d", len(results))
	t.Logf("Parseable:                  %d", parseable)
	t.Logf("Parser errors:              %d", parserErrors)
	t.Logf("Unsupported explicit:       %d", unsupported)
	t.Logf("Normalized as ALTER TABLE:  %d", normalized)
	t.Logf("Finding covered:            %d", findingCovered)
	t.Logf("Normalized silent pass:     %d", silentPass)
	t.Logf("Unclassified:               %d", unclassified)

	const (
		expectTotal            = 42
		expectParseable        = 42
		expectParserErrors     = 0
		expectUnsupported      = 0
		expectFindingCovered   = 41
		expectNormalizedSilent = 1
	)

	if got := len(results); got != expectTotal {
		t.Errorf("ALTER TABLE census total: got %d, want %d", got, expectTotal)
	}
	if parseable != expectParseable {
		t.Errorf("ALTER TABLE census parseable: got %d, want %d", parseable, expectParseable)
	}
	if parserErrors != expectParserErrors {
		t.Errorf("ALTER TABLE census parser errors: got %d, want %d", parserErrors, expectParserErrors)
	}
	if unsupported != expectUnsupported {
		t.Errorf("ALTER TABLE census unsupported: got %d, want %d", unsupported, expectUnsupported)
	}
	if findingCovered != expectFindingCovered {
		t.Errorf("ALTER TABLE census finding covered: got %d, want %d", findingCovered, expectFindingCovered)
	}
	if silentPass != expectNormalizedSilent {
		t.Errorf("ALTER TABLE census normalized silent pass: got %d, want %d", silentPass, expectNormalizedSilent)
	}
}

func classifyAlterTableCensusResult(t *testing.T, name, sql string) alterTableCensusResult {
	t.Helper()
	res := alterTableCensusResult{Name: name}

	parsed, parseErr := Parse(context.Background(), sql, spec.DialectPostgreSQL)
	if parseErr != nil {
		res.Status = alterTableStatusParserError
		t.Logf("alter-census: %-40s → parser-error: %v", name, parseErr)
		return res
	}
	res.ParseOK = true

	statements, extractErr := Extract(context.Background(), parsed)
	if extractErr != nil {
		res.Status = alterTableStatusUnclassified
		t.Logf("alter-census: %-40s → extract-error: %v", name, extractErr)
		return res
	}

	var supported *spec.Statement
	for i := range statements {
		if statements[i].Unsupported == nil {
			s := statements[i]
			supported = &s
			break
		}
	}

	if supported == nil {
		res.Unsupported = true
		if len(statements) > 0 && statements[0].Unsupported != nil {
			res.UnsupportedFeat = statements[0].Unsupported.Feature
			res.UnsupportedWhy = statements[0].Unsupported.Reason
		}
		if len(statements) > 0 {
			res.Kind = string(statements[0].Kind)
		}
		res.Status = alterTableStatusUnsupportedExp
		t.Logf("alter-census: %-40s → unsupported(%s): %s", name, res.UnsupportedFeat, res.UnsupportedWhy)
		return res
	}

	res.Normalized = true
	res.Kind = string(supported.Kind)
	if supported.DDL != nil {
		res.DDLOperation = string(supported.DDL.Operation)
		res.AlterActions = collectAlterActions(supported.DDL)
	}

	result, auditErr := AuditSQL(context.Background(), Request{
		SQL:     sql,
		Dialect: spec.DialectPostgreSQL,
	})
	if auditErr != nil {
		t.Logf("alter-census: %-40s → audit-error: %v", name, auditErr)
	}

	// Collect findings from audit result — inline to avoid report package import.
	seen := make(map[string]struct{})
	if result.Statements != nil {
		for _, s := range result.Statements {
			for _, f := range s.Findings {
				seen[f.RuleID] = struct{}{}
			}
		}
	}
	for _, f := range result.GlobalFindings {
		seen[f.RuleID] = struct{}{}
	}
	ids := make([]string, 0, len(seen))
	for id := range seen {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	res.FindingRuleIDs = ids

	if res.DDLOperation == "alter_table" && len(res.FindingRuleIDs) > 0 {
		res.Status = alterTableStatusFindingCovered
	} else if res.DDLOperation == "alter_table" && len(res.FindingRuleIDs) == 0 {
		res.Status = alterTableStatusNormalizedSilent
	} else {
		res.Status = alterTableStatusUnclassified
	}

	t.Logf("alter-census: %-40s → %s | op=%s alter=%v findings=%v",
		name, res.Status, res.DDLOperation, res.AlterActions, res.FindingRuleIDs)
	return res
}

func collectAlterActions(ddl *spec.DDL) []string {
	if ddl == nil {
		return nil
	}
	actions := make([]string, 0, len(ddl.Alter))
	for _, a := range ddl.Alter {
		actions = append(actions, a.Action)
	}
	return actions
}

func logAlterTableCensusTable(t *testing.T, results []alterTableCensusResult) {
	t.Helper()
	t.Log("")
	t.Log("=== PostgreSQL ALTER TABLE Coverage Census ===")
	t.Log("")
	t.Logf("%-40s | %-4s | %-22s | %-20s | %-20s | %s",
		"Form", "OK?", "Status", "DDL Op", "Alter Actions", "Finding Rule IDs")
	t.Log(strings.Repeat("-", 160))

	sorted := make([]alterTableCensusResult, len(results))
	copy(sorted, results)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for _, r := range sorted {
		parseOK := "yes"
		if !r.ParseOK {
			parseOK = "no"
		}

		detail := strings.Join(r.FindingRuleIDs, ", ")
		if detail == "" {
			detail = "(none)"
		}
		if r.Unsupported {
			detail = fmt.Sprintf("unsupported: %s (%s)", r.UnsupportedFeat, r.UnsupportedWhy)
		}

		actions := strings.Join(r.AlterActions, ", ")
		if actions == "" {
			actions = "-"
		}

		t.Logf("%-40s | %-4s | %-22s | %-20s | %-20s | %s",
			r.Name, parseOK, r.Status, r.DDLOperation, actions, detail)
	}
}
