//go:build postgresql

package audit

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/report"
	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
)

type alterTableResidualClassification string

const (
	residualFindingCovered   alterTableResidualClassification = "finding_covered"
	residualNormalizedSilent alterTableResidualClassification = "normalized_silent"
	residualUnsupportedBound alterTableResidualClassification = "unsupported_boundary"
	residualParserError      alterTableResidualClassification = "parser_error"
	residualUnclassified     alterTableResidualClassification = "unclassified"
)

type alterTableResidualCase struct {
	Family string
	Name   string
	SQL    string
}

type alterTableResidualResult struct {
	Family             string
	Name               string
	Classification     alterTableResidualClassification
	UnsupportedFeature string
	DDLOperation       string
	AlterActions       []string
	OptionKeys         []string
	FindingRuleIDs     []string
}

var pgAlterTableResidualCases = []alterTableResidualCase{
	// --- Baseline anchors ---
	{Family: "baseline_anchors", Name: "DROP COLUMN email", SQL: "ALTER TABLE users DROP COLUMN email"},
	{Family: "baseline_anchors", Name: "RENAME COLUMN email TO mail", SQL: "ALTER TABLE users RENAME COLUMN email TO mail"},
	{Family: "baseline_anchors", Name: "ADD COLUMN email NOT NULL DEFAULT", SQL: "ALTER TABLE users ADD COLUMN email text NOT NULL DEFAULT ''"},
	{Family: "baseline_anchors", Name: "ALTER COLUMN TYPE USING", SQL: "ALTER TABLE users ALTER COLUMN name TYPE jsonb USING to_jsonb(name)"},
	{Family: "baseline_anchors", Name: "ADD CHECK NOT VALID", SQL: "ALTER TABLE products ADD CONSTRAINT chk_price CHECK (price > 0) NOT VALID"},
	{Family: "baseline_anchors", Name: "VALIDATE CONSTRAINT", SQL: "ALTER TABLE users VALIDATE CONSTRAINT chk_price"},
	{Family: "baseline_anchors", Name: "ENABLE TRIGGER ALL", SQL: "ALTER TABLE users ENABLE TRIGGER ALL"},
	{Family: "baseline_anchors", Name: "REPLICA IDENTITY USING INDEX", SQL: "ALTER TABLE users REPLICA IDENTITY USING INDEX users_replica_identity_idx"},
	{Family: "baseline_anchors", Name: "ATTACH PARTITION range", SQL: "ALTER TABLE measurement ATTACH PARTITION measurement_y2026m04 FOR VALUES FROM ('2026-04-01') TO ('2026-05-01')"},
	{Family: "baseline_anchors", Name: "SET TABLESPACE", SQL: "ALTER TABLE users SET TABLESPACE fastspace"},

	// --- Column attributes ---
	{Family: "column_attributes", Name: "SET STATISTICS 100", SQL: "ALTER TABLE users ALTER COLUMN email SET STATISTICS 100"},
	{Family: "column_attributes", Name: "SET STATISTICS DEFAULT", SQL: "ALTER TABLE users ALTER COLUMN email SET STATISTICS DEFAULT"},
	{Family: "column_attributes", Name: "SET n_distinct", SQL: "ALTER TABLE users ALTER COLUMN email SET (n_distinct = -1)"},
	{Family: "column_attributes", Name: "RESET n_distinct", SQL: "ALTER TABLE users ALTER COLUMN email RESET (n_distinct)"},
	{Family: "column_attributes", Name: "SET STORAGE EXTERNAL", SQL: "ALTER TABLE users ALTER COLUMN bio SET STORAGE EXTERNAL"},
	{Family: "column_attributes", Name: "SET STORAGE DEFAULT", SQL: "ALTER TABLE users ALTER COLUMN bio SET STORAGE DEFAULT"},
	{Family: "column_attributes", Name: "SET COMPRESSION lz4", SQL: "ALTER TABLE users ALTER COLUMN bio SET COMPRESSION lz4"},
	{Family: "column_attributes", Name: "SET EXPRESSION computed", SQL: "ALTER TABLE users ALTER COLUMN full_name SET EXPRESSION AS (first_name || ' ' || last_name)"},
	{Family: "column_attributes", Name: "DROP EXPRESSION IF EXISTS", SQL: "ALTER TABLE users ALTER COLUMN full_name DROP EXPRESSION IF EXISTS"},
	{Family: "column_attributes", Name: "ADD GENERATED BY DEFAULT AS IDENTITY", SQL: "ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"},
	{Family: "column_attributes", Name: "SET GENERATED ALWAYS", SQL: "ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS"},
	{Family: "column_attributes", Name: "SET INCREMENT BY 10", SQL: "ALTER TABLE users ALTER COLUMN id SET INCREMENT BY 10"},
	{Family: "column_attributes", Name: "RESTART WITH 1000", SQL: "ALTER TABLE users ALTER COLUMN id RESTART WITH 1000"},
	{Family: "column_attributes", Name: "DROP IDENTITY IF EXISTS", SQL: "ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS"},

	// --- Constraints ---
	{Family: "constraints", Name: "UNIQUE NULLS NOT DISTINCT", SQL: "ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE NULLS NOT DISTINCT (email)"},
	{Family: "constraints", Name: "PRIMARY KEY INCLUDE", SQL: "ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id) INCLUDE (email)"},
	{Family: "constraints", Name: "EXCLUDE USING gist", SQL: "ALTER TABLE bookings ADD CONSTRAINT bookings_no_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&)"},
	{Family: "constraints", Name: "NOT NULL NOT VALID", SQL: "ALTER TABLE users ADD CONSTRAINT users_email_nn NOT NULL email NOT VALID"},
	{Family: "constraints", Name: "UNIQUE USING INDEX", SQL: "ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE USING INDEX users_email_idx"},
	{Family: "constraints", Name: "PRIMARY KEY USING INDEX", SQL: "ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY USING INDEX users_id_idx"},
	{Family: "constraints", Name: "ALTER CONSTRAINT DEFERRABLE", SQL: "ALTER TABLE orders ALTER CONSTRAINT orders_user_id_fkey DEFERRABLE"},
	{Family: "constraints", Name: "ALTER CONSTRAINT INITIALLY DEFERRED", SQL: "ALTER TABLE orders ALTER CONSTRAINT orders_user_id_fkey INITIALLY DEFERRED"},
	{Family: "constraints", Name: "ALTER CONSTRAINT NOT ENFORCED", SQL: "ALTER TABLE orders ALTER CONSTRAINT orders_user_id_fkey NOT ENFORCED"},
	{Family: "constraints", Name: "ALTER CONSTRAINT INHERIT", SQL: "ALTER TABLE users ALTER CONSTRAINT users_email_nn INHERIT"},
	{Family: "constraints", Name: "ALTER CONSTRAINT NO INHERIT", SQL: "ALTER TABLE users ALTER CONSTRAINT users_email_nn NO INHERIT"},
	{Family: "constraints", Name: "DROP CONSTRAINT IF EXISTS CASCADE", SQL: "ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key CASCADE"},

	// --- Trigger / rule / RLS ---
	{Family: "trigger_rule_rls", Name: "ENABLE REPLICA TRIGGER", SQL: "ALTER TABLE users ENABLE REPLICA TRIGGER trg_users_audit"},
	{Family: "trigger_rule_rls", Name: "ENABLE ALWAYS TRIGGER", SQL: "ALTER TABLE users ENABLE ALWAYS TRIGGER trg_users_audit"},
	{Family: "trigger_rule_rls", Name: "DISABLE RULE", SQL: "ALTER TABLE users DISABLE RULE users_rewrite_rule"},
	{Family: "trigger_rule_rls", Name: "ENABLE RULE", SQL: "ALTER TABLE users ENABLE RULE users_rewrite_rule"},
	{Family: "trigger_rule_rls", Name: "ENABLE REPLICA RULE", SQL: "ALTER TABLE users ENABLE REPLICA RULE users_rewrite_rule"},
	{Family: "trigger_rule_rls", Name: "ENABLE ALWAYS RULE", SQL: "ALTER TABLE users ENABLE ALWAYS RULE users_rewrite_rule"},
	{Family: "trigger_rule_rls", Name: "ENABLE ROW LEVEL SECURITY", SQL: "ALTER TABLE users ENABLE ROW LEVEL SECURITY"},
	{Family: "trigger_rule_rls", Name: "DISABLE ROW LEVEL SECURITY", SQL: "ALTER TABLE users DISABLE ROW LEVEL SECURITY"},
	{Family: "trigger_rule_rls", Name: "FORCE ROW LEVEL SECURITY", SQL: "ALTER TABLE users FORCE ROW LEVEL SECURITY"},
	{Family: "trigger_rule_rls", Name: "NO FORCE ROW LEVEL SECURITY", SQL: "ALTER TABLE users NO FORCE ROW LEVEL SECURITY"},

	// --- Table properties ---
	{Family: "table_properties", Name: "CLUSTER ON", SQL: "ALTER TABLE users CLUSTER ON users_email_idx"},
	{Family: "table_properties", Name: "SET WITHOUT CLUSTER", SQL: "ALTER TABLE users SET WITHOUT CLUSTER"},
	{Family: "table_properties", Name: "SET WITHOUT OIDS", SQL: "ALTER TABLE users SET WITHOUT OIDS"},
	{Family: "table_properties", Name: "SET ACCESS METHOD heap", SQL: "ALTER TABLE users SET ACCESS METHOD heap"},
	{Family: "table_properties", Name: "SET ACCESS METHOD DEFAULT", SQL: "ALTER TABLE users SET ACCESS METHOD DEFAULT"},
	{Family: "table_properties", Name: "SET fillfactor", SQL: "ALTER TABLE users SET (fillfactor = 70)"},
	{Family: "table_properties", Name: "RESET fillfactor", SQL: "ALTER TABLE users RESET (fillfactor)"},
	{Family: "table_properties", Name: "INHERIT", SQL: "ALTER TABLE child_users INHERIT users"},
	{Family: "table_properties", Name: "NO INHERIT", SQL: "ALTER TABLE child_users NO INHERIT users"},
	{Family: "table_properties", Name: "OF type", SQL: "ALTER TABLE users OF user_type"},
	{Family: "table_properties", Name: "NOT OF", SQL: "ALTER TABLE users NOT OF"},
	{Family: "table_properties", Name: "ALL IN TABLESPACE SET", SQL: "ALTER TABLE ALL IN TABLESPACE pg_default SET TABLESPACE fastspace"},

	// --- Partition details ---
	{Family: "partition_details", Name: "ATTACH DEFAULT", SQL: "ALTER TABLE measurement ATTACH PARTITION measurement_default DEFAULT"},
	{Family: "partition_details", Name: "ATTACH LIST", SQL: "ALTER TABLE measurement ATTACH PARTITION measurement_p1 FOR VALUES IN ('north')"},
	{Family: "partition_details", Name: "ATTACH HASH", SQL: "ALTER TABLE measurement ATTACH PARTITION measurement_h1 FOR VALUES WITH (MODULUS 4, REMAINDER 0)"},
	{Family: "partition_details", Name: "DETACH CONCURRENTLY", SQL: "ALTER TABLE measurement DETACH PARTITION measurement_y2026m04 CONCURRENTLY"},
	{Family: "partition_details", Name: "DETACH FINALIZE", SQL: "ALTER TABLE measurement DETACH PARTITION measurement_y2026m04 FINALIZE"},

	// --- Multi-command ---
	{Family: "multi_command", Name: "ADD two columns", SQL: "ALTER TABLE users ADD COLUMN first_name text, ADD COLUMN last_name text"},
	{Family: "multi_command", Name: "ADD + ALTER", SQL: "ALTER TABLE users ADD COLUMN status text, ALTER COLUMN status SET NOT NULL"},
	{Family: "multi_command", Name: "SET DEFAULT + VALIDATE", SQL: "ALTER TABLE users ALTER COLUMN status SET DEFAULT 'active', VALIDATE CONSTRAINT users_status_check"},
}

func TestPostgreSQLAlterTableResidualCensus(t *testing.T) {
	t.Parallel()

	results := make([]alterTableResidualResult, 0, len(pgAlterTableResidualCases))

	for _, tc := range pgAlterTableResidualCases {
		res := classifyAlterTableResidualCase(t, tc)
		results = append(results, res)
	}

	logAlterTableResidualResults(t, results)
	assertAlterTableResidualResults(t, results)
}

func classifyAlterTableResidualCase(t *testing.T, tc alterTableResidualCase) alterTableResidualResult {
	t.Helper()
	res := alterTableResidualResult{
		Family: tc.Family,
		Name:   tc.Name,
	}

	parsed, parseErr := Parse(context.Background(), tc.SQL, spec.DialectPostgreSQL)
	if parseErr != nil {
		res.Classification = residualParserError
		t.Logf("residual-census: %-30s %-40s → parser-error: %v", tc.Family, tc.Name, parseErr)
		return res
	}

	statements, extractErr := Extract(context.Background(), parsed)
	if extractErr != nil {
		res.Classification = residualUnclassified
		t.Logf("residual-census: %-30s %-40s → extract-error: %v", tc.Family, tc.Name, extractErr)
		return res
	}

	var supported *spec.Statement
	for i := range statements {
		if statements[i].Unsupported == nil {
			s := statements[i]
			supported = &s
			break
		}
	}

	if supported == nil {
		res.Classification = residualUnsupportedBound
		if len(statements) > 0 && statements[0].Unsupported != nil {
			res.UnsupportedFeature = statements[0].Unsupported.Feature
		}
		t.Logf("residual-census: %-30s %-40s → unsupported(%s)", tc.Family, tc.Name, res.UnsupportedFeature)
		return res
	}

	if supported.DDL != nil {
		res.DDLOperation = string(supported.DDL.Operation)
		res.AlterActions = collectResidualAlterActions(supported.DDL)
		res.OptionKeys = collectResidualOptionKeys(supported.DDL)
	}

	result, auditErr := AuditSQL(context.Background(), Request{
		SQL:     tc.SQL,
		Dialect: spec.DialectPostgreSQL,
	})
	if auditErr != nil {
		t.Logf("residual-census: %-30s %-40s → audit-error: %v", tc.Family, tc.Name, auditErr)
	}

	res.FindingRuleIDs = collectResidualFindingRuleIDs(result)

	if res.DDLOperation == "alter_table" && len(res.FindingRuleIDs) > 0 {
		res.Classification = residualFindingCovered
	} else if res.DDLOperation == "alter_table" && len(res.FindingRuleIDs) == 0 {
		res.Classification = residualNormalizedSilent
	} else {
		res.Classification = residualUnclassified
	}

	t.Logf("residual-census: %-30s %-40s → %s | op=%s alter=%v opts=%v findings=%v",
		tc.Family, tc.Name, res.Classification, res.DDLOperation,
		res.AlterActions, res.OptionKeys, res.FindingRuleIDs)
	return res
}

func collectResidualAlterActions(ddl *spec.DDL) []string {
	if ddl == nil {
		return nil
	}
	actions := make([]string, 0, len(ddl.Alter))
	for _, a := range ddl.Alter {
		actions = append(actions, a.Action)
	}
	return actions
}

func collectResidualOptionKeys(ddl *spec.DDL) []string {
	if ddl == nil {
		return nil
	}
	seen := make(map[string]struct{})
	for k := range ddl.Options {
		seen[k] = struct{}{}
	}
	for _, a := range ddl.Alter {
		for k := range a.Options {
			seen[k] = struct{}{}
		}
	}
	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func collectResidualFindingRuleIDs(result report.Result) []string {
	seen := make(map[string]struct{})
	if result.Statements != nil {
		for _, s := range result.Statements {
			for _, f := range s.Findings {
				seen[f.RuleID] = struct{}{}
			}
		}
	}
	for _, f := range result.GlobalFindings {
		seen[f.RuleID] = struct{}{}
	}
	ids := make([]string, 0, len(seen))
	for id := range seen {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

func logAlterTableResidualResults(t *testing.T, results []alterTableResidualResult) {
	t.Helper()
	t.Log("")
	t.Log("=== PostgreSQL ALTER TABLE Residual Census ===")
	t.Log("")
	t.Logf("%-20s %-40s %-22s %-20s %-30s %-20s %s",
		"family", "name", "classification", "ddl_operation", "alter_actions", "option_keys", "finding_rule_ids")
	t.Log(strings.Repeat("-", 200))

	sorted := make([]alterTableResidualResult, len(results))
	copy(sorted, results)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Family != sorted[j].Family {
			return sorted[i].Family < sorted[j].Family
		}
		return sorted[i].Name < sorted[j].Name
	})

	for _, r := range sorted {
		actions := strings.Join(r.AlterActions, ", ")
		if actions == "" {
			actions = "-"
		}
		optKeys := strings.Join(r.OptionKeys, ", ")
		if optKeys == "" {
			optKeys = "-"
		}
		findings := strings.Join(r.FindingRuleIDs, ", ")
		if findings == "" {
			findings = "-"
		}
		if r.Classification == residualUnsupportedBound {
			findings = fmt.Sprintf("unsupported: %s", r.UnsupportedFeature)
		}

		t.Logf("%-20s %-40s %-22s %-20s %-30s %-20s %s",
			r.Family, r.Name, r.Classification, r.DDLOperation, actions, optKeys, findings)
	}

	// Summary counts.
	counts := make(map[alterTableResidualClassification]int)
	familyCounts := make(map[string]map[alterTableResidualClassification]int)
	for _, r := range results {
		counts[r.Classification]++
		if familyCounts[r.Family] == nil {
			familyCounts[r.Family] = make(map[alterTableResidualClassification]int)
		}
		familyCounts[r.Family][r.Classification]++
	}

	t.Log("")
	t.Log("=== Residual Census Summary ===")
	t.Logf("Total cases:            %d", len(results))
	t.Logf("finding_covered:         %d", counts[residualFindingCovered])
	t.Logf("normalized_silent:       %d", counts[residualNormalizedSilent])
	t.Logf("unsupported_boundary:    %d", counts[residualUnsupportedBound])
	t.Logf("parser_error:            %d", counts[residualParserError])
	t.Logf("unclassified:            %d", counts[residualUnclassified])

	t.Log("")
	t.Log("=== Counts by Family ===")
	families := make([]string, 0, len(familyCounts))
	for f := range familyCounts {
		families = append(families, f)
	}
	sort.Strings(families)
	for _, f := range families {
		fc := familyCounts[f]
		total := 0
		for _, c := range fc {
			total += c
		}
		t.Logf("  %-20s total=%d  finding=%d silent=%d unsupported=%d parser_err=%d unclassified=%d",
			f, total,
			fc[residualFindingCovered], fc[residualNormalizedSilent],
			fc[residualUnsupportedBound], fc[residualParserError], fc[residualUnclassified])
	}
}

func assertAlterTableResidualResults(t *testing.T, results []alterTableResidualResult) {
	t.Helper()

	if got := len(results); got != len(pgAlterTableResidualCases) {
		t.Errorf("residual census: got %d results, expected %d cases", got, len(pgAlterTableResidualCases))
	}

	counts := make(map[alterTableResidualClassification]int)
	for _, r := range results {
		counts[r.Classification]++
	}

	if counts[residualUnclassified] != 0 {
		var unclassified []string
		for _, r := range results {
			if r.Classification == residualUnclassified {
				unclassified = append(unclassified, fmt.Sprintf("%s/%s", r.Family, r.Name))
			}
		}
		t.Errorf("residual census: %d unclassified cases: %s", counts[residualUnclassified], strings.Join(unclassified, ", "))
	}
}
