//go:build postgresql

package audit

import (
	"context"
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
)

func TestAuditSQLPostgreSQLGeneratedIdentityRuleCoverage(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name              string
		sql               string
		wantRuleID        string
		wantAction        string
		wantGeneratedWhen string
	}{
		{
			name:       "drop_expression",
			sql:        "ALTER TABLE users ALTER COLUMN full_name DROP EXPRESSION;",
			wantRuleID: "ddl.alter.drop_expression.forbid",
			wantAction: "drop_expression",
		},
		{
			name:              "set_generated_by_default",
			sql:               "ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;",
			wantRuleID:        "ddl.alter.set_generated.forbid",
			wantAction:        "set_generated",
			wantGeneratedWhen: "d",
		},
		{
			name:              "set_generated_always",
			sql:               "ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS;",
			wantRuleID:        "ddl.alter.set_generated.forbid",
			wantAction:        "set_generated",
			wantGeneratedWhen: "a",
		},
		{
			name:       "drop_identity",
			sql:        "ALTER TABLE users ALTER COLUMN id DROP IDENTITY;",
			wantRuleID: "ddl.alter.drop_identity.forbid",
			wantAction: "drop_identity",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt := tt
			t.Parallel()
			result, err := AuditSQL(context.Background(), Request{
				SQL:     tt.sql,
				Dialect: spec.DialectPostgreSQL,
			})
			if err != nil {
				t.Fatalf("audit sql: %v", err)
			}
			if len(result.Unsupported) != 0 {
				t.Fatalf("expected 0 unsupported, got %#v", result.Unsupported)
			}
			if len(result.Statements) != 1 {
				t.Fatalf("expected 1 statement, got %d", len(result.Statements))
			}

			// Must have the expected forbid rule finding.
			found := false
			for _, f := range result.Statements[0].Findings {
				if f.RuleID == tt.wantRuleID {
					found = true
					break
				}
			}
			if !found {
				t.Fatalf("expected finding with rule %q, got %#v", tt.wantRuleID, result.Statements[0].Findings)
			}

			// Verify spec-level facts are still correct.
			stmt, ok := corpusExtractStatement(t, tt.sql, spec.DialectPostgreSQL)
			if !ok {
				t.Fatal("expected supported statement")
			}
			if stmt.DDL == nil {
				t.Fatal("expected DDL payload")
			}
			var matched *spec.Alter
			for i := range stmt.DDL.Alter {
				if stmt.DDL.Alter[i].Action == tt.wantAction {
					matched = &stmt.DDL.Alter[i]
					break
				}
			}
			if matched == nil {
				t.Fatalf("expected alter action %q, got %+v", tt.wantAction, stmt.DDL.Alter)
			}
			if tt.wantGeneratedWhen != "" {
				if matched.Options["generated_when"] != tt.wantGeneratedWhen {
					t.Fatalf("expected generated_when %q, got %#v", tt.wantGeneratedWhen, matched.Options)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// v0.33.0 Task 3: Service tests — unsupported metadata surfacing
// ---------------------------------------------------------------------------

func TestAuditSQLPostgreSQLGeneratedIdentityNarrowNowSupported(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name              string
		sql               string
		wantColumnName    string
		wantGeneratedWhen string
		wantIsIdentity    bool
		wantIdentityOpts  map[string]any
		isAlter           bool
	}{
		{
			name:              "generated_stored_column",
			sql:               `CREATE TABLE t (first_name text, full_name text GENERATED ALWAYS AS (first_name) STORED);`,
			wantColumnName:    "full_name",
			wantGeneratedWhen: "a",
		},
		{
			name:              "generated_always_as_identity",
			sql:               `CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY);`,
			wantColumnName:    "id",
			wantGeneratedWhen: "a",
			wantIsIdentity:    true,
		},
		{
			name:              "generated_by_default_as_identity_with_options",
			sql:               `CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5 CACHE 20 CYCLE));`,
			wantColumnName:    "id",
			wantGeneratedWhen: "d",
			wantIsIdentity:    true,
			wantIdentityOpts: map[string]any{
				"start":     int32(10),
				"increment": int32(5),
				"cache":     int32(20),
				"cycle":     true,
			},
		},
		{
			name:              "alter_table_add_generated_column",
			sql:               `ALTER TABLE t ADD COLUMN full_name text GENERATED ALWAYS AS (first_name) STORED;`,
			wantColumnName:    "full_name",
			wantGeneratedWhen: "a",
			isAlter:           true,
		},
		{
			name:              "alter_table_add_identity_column",
			sql:               `ALTER TABLE t ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY;`,
			wantColumnName:    "id",
			wantGeneratedWhen: "a",
			wantIsIdentity:    true,
			isAlter:           true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt := tt
			t.Parallel()
			result, err := AuditSQL(context.Background(), Request{
				SQL:     tt.sql,
				Dialect: spec.DialectPostgreSQL,
			})
			if err != nil {
				t.Fatalf("expected supported, got error: %v", err)
			}
			if len(result.Unsupported) != 0 {
				t.Fatalf("expected 0 unsupported, got %#v", result.Unsupported)
			}

			stmt, ok := corpusExtractStatement(t, tt.sql, spec.DialectPostgreSQL)
			if !ok {
				t.Fatal("expected supported statement")
			}
			if stmt.DDL == nil {
				t.Fatal("expected DDL payload")
			}

			var col *spec.Column
			if tt.isAlter {
				for i := range stmt.DDL.Alter {
					alt := &stmt.DDL.Alter[i]
					if alt.Column != nil && alt.Column.Definition != nil && alt.Column.Definition.Name == tt.wantColumnName {
						col = alt.Column.Definition
						break
					}
				}
			} else {
				for i := range stmt.DDL.Columns {
					if stmt.DDL.Columns[i].Name == tt.wantColumnName {
						col = &stmt.DDL.Columns[i]
						break
					}
				}
			}
			if col == nil {
				t.Fatalf("expected column %q not found", tt.wantColumnName)
			}

			if col.GeneratedWhen != tt.wantGeneratedWhen {
				t.Fatalf("expected GeneratedWhen %q, got %q", tt.wantGeneratedWhen, col.GeneratedWhen)
			}
			if col.IsIdentity != tt.wantIsIdentity {
				t.Fatalf("expected IsIdentity %v, got %v", tt.wantIsIdentity, col.IsIdentity)
			}

			if tt.wantIdentityOpts != nil {
				if col.IdentityOptions == nil {
					t.Fatal("expected IdentityOptions to be populated")
				}
				for key, wantVal := range tt.wantIdentityOpts {
					actVal, ok := col.IdentityOptions[key]
					if !ok {
						t.Fatalf("expected identity_options key %q, got %+v", key, col.IdentityOptions)
					}
					if !serviceMetadataValueEqual(wantVal, actVal) {
						t.Fatalf("identity_options[%q]: expected %v (%T), got %v (%T)", key, wantVal, wantVal, actVal, actVal)
					}
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// v0.37.0 Task 3: Service tests — primary-key rule coverage
// ---------------------------------------------------------------------------

// TestAuditSQLPostgreSQLPrimaryKeyRuleCoverage proves that the PostgreSQL
// extractor now populates DDL.PrimaryKey facts so existing primary-key rules
// can fire through the full AuditSQL pipeline.
