rules:
  ddl.table.comment.require:
    enabled: true
    level: warning
    params:
      required: true

  ddl.table.name.max_length:
    enabled: true
    level: blocker
    params:
      limit: 64

  ddl.table.primary_key.columns.max_count:
    enabled: true
    level: warning
    params:
      limit: 1

  ddl.table.primary_key.require:
    enabled: true
    level: blocker
    params:
      required: true

  dml.insert.on_duplicate.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.insert.rows.max_count:
    enabled: true
    level: warning
    params:
      limit: 100

  dml.insert.select.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.join.on.require:
    enabled: true
    level: blocker
    params:
      required: true

  dml.limit.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  dml.order_by.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  dml.replace.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.subquery.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.where.require:
    enabled: true
    level: blocker
    params:
      required: true
