rules:
  ddl.alter.change_column.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.alter.drop_column.forbid:
    enabled: true
    level: warning
    params:
      forbid: false

  ddl.alter.drop_index.forbid:
    enabled: true
    level: warning
    params:
      forbid: false

  ddl.alter.drop_primary_key.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.alter.modify_column.forbid:
    enabled: true
    level: warning
    params:
      forbid: false

  ddl.alter.rename_column.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.alter.rename_table.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.column.comment.require:
    enabled: true
    level: warning
    params:
      required: true

  ddl.column.default.require:
    enabled: true
    level: warning
    params:
      required: true

  ddl.column.float_double.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  ddl.column.name.max_length:
    enabled: true
    level: blocker
    params:
      limit: 64

  ddl.column.not_null.require:
    enabled: true
    level: warning
    params:
      allow_time_null: true
      required: true

  ddl.column.varchar.max_length:
    enabled: true
    level: blocker
    params:
      limit: 16383

  ddl.index.columns.max_count:
    enabled: true
    level: warning
    params:
      limit: 8

  ddl.index.duplicate.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  ddl.index.fulltext.prefix.require:
    enabled: true
    level: warning
    params:
      prefix: full_
      required: true

  ddl.index.secondary.prefix.require:
    enabled: true
    level: warning
    params:
      prefix: idx_
      required: true

  ddl.index.total.max_count:
    enabled: true
    level: warning
    params:
      limit: 12

  ddl.index.unique.prefix.require:
    enabled: true
    level: warning
    params:
      prefix: uniq_
      required: true

  ddl.table.audit_columns.require:
    enabled: true
    level: warning
    params:
      required: true

  ddl.table.charset.allowlist:
    enabled: true
    level: blocker
    params:
      values: [utf8 utf8mb4]

  ddl.table.columns.min_count:
    enabled: true
    level: blocker
    params:
      limit: 1

  ddl.table.comment.max_length:
    enabled: true
    level: warning
    params:
      limit: 128

  ddl.table.comment.require:
    enabled: true
    level: warning
    params:
      required: true

  ddl.table.create_as.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.table.create_like.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.table.engine.allowlist:
    enabled: true
    level: blocker
    params:
      values: [InnoDB]

  ddl.table.foreign_key.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.table.name.max_length:
    enabled: true
    level: blocker
    params:
      limit: 64

  ddl.table.partition.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  ddl.table.primary_key.columns.max_count:
    enabled: true
    level: warning
    params:
      limit: 1

  ddl.table.primary_key.require:
    enabled: true
    level: blocker
    params:
      required: true

  dml.insert.on_duplicate.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.insert.rows.max_count:
    enabled: true
    level: warning
    params:
      limit: 100

  dml.insert.select.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.join.on.require:
    enabled: true
    level: blocker
    params:
      required: true

  dml.limit.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  dml.order_by.forbid:
    enabled: true
    level: warning
    params:
      forbid: true

  dml.replace.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.subquery.forbid:
    enabled: true
    level: blocker
    params:
      forbid: true

  dml.where.require:
    enabled: true
    level: blocker
    params:
      required: true
