//go:build postgresql

package postgresql

import (
	"fmt"
	"strings"
	"testing"

	pg_query "github.com/pganalyze/pg_query_go/v6"
)

var pgAlterTableRemainingBoundaryCases = []struct {
	family string
	name   string
	sql    string
}{
	{family: "column_attributes", name: "SET EXPRESSION computed", sql: "ALTER TABLE users ALTER COLUMN full_name SET EXPRESSION AS (first_name || ' ' || last_name)"},
	{family: "column_attributes", name: "ADD GENERATED BY DEFAULT AS IDENTITY", sql: "ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"},
	{family: "constraints", name: "EXCLUDE USING gist", sql: "ALTER TABLE bookings ADD CONSTRAINT bookings_no_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&)"},
	{family: "constraints", name: "ALTER CONSTRAINT DEFERRABLE", sql: "ALTER TABLE orders ALTER CONSTRAINT orders_user_id_fkey DEFERRABLE"},
	{family: "constraints", name: "ALTER CONSTRAINT INITIALLY DEFERRED", sql: "ALTER TABLE orders ALTER CONSTRAINT orders_user_id_fkey INITIALLY DEFERRED"},
	{family: "table_properties", name: "SET WITHOUT OIDS", sql: "ALTER TABLE users SET WITHOUT OIDS"},
	{family: "table_properties", name: "ALL IN TABLESPACE SET", sql: "ALTER TABLE ALL IN TABLESPACE pg_default SET TABLESPACE fastspace"},
}

type remainingBoundaryASTFact struct {
	Family      string
	Name        string
	SQL         string
	ParseOK     bool
	TopKind     string
	Table       string
	CmdCount    int
	SubtypeName string
	SubtypeNum  int32
	CmdName     string
	HasDef      bool
	DefKind     string
	DefProto    string
	CmdProto    string

	// For AlterTableMoveAllStmt (ALL IN TABLESPACE)
	IsMoveAll    bool
	OrigTablespc string
	NewTablespc  string
}

func remainingBoundaryASTFactForCase(t *testing.T, tc struct {
	family string
	name   string
	sql    string
}) remainingBoundaryASTFact {
	t.Helper()

	fact := remainingBoundaryASTFact{
		Family: tc.family,
		Name:   tc.name,
		SQL:    tc.sql,
	}

	tree, err := pg_query.Parse(tc.sql)
	if err != nil {
		t.Logf("PARSE FAILED for %q: %v", tc.name, err)
		return fact
	}
	fact.ParseOK = true

	if len(tree.GetStmts()) != 1 {
		t.Fatalf("%s: expected 1 statement, got %d", tc.name, len(tree.GetStmts()))
	}

	node := tree.GetStmts()[0].GetStmt()
	if node == nil {
		t.Fatalf("%s: nil statement node", tc.name)
	}

	switch node.GetNode().(type) {
	case *pg_query.Node_AlterTableStmt:
		fact.TopKind = "AlterTableStmt"
	case *pg_query.Node_AlterTableMoveAllStmt:
		fact.TopKind = "AlterTableMoveAllStmt"
		fact.IsMoveAll = true
		mvStmt := node.GetNode().(*pg_query.Node_AlterTableMoveAllStmt).AlterTableMoveAllStmt
		if mvStmt != nil {
			fact.OrigTablespc = mvStmt.GetOrigTablespacename()
			fact.NewTablespc = mvStmt.GetNewTablespacename()
		}
		return fact
	default:
		fact.TopKind = strings.TrimPrefix(fmt.Sprintf("%T", node.GetNode()), "*pg_query.Node_")
		return fact
	}

	atStmt := node.GetNode().(*pg_query.Node_AlterTableStmt).AlterTableStmt
	if atStmt == nil {
		t.Fatalf("%s: AlterTableStmt is nil", tc.name)
	}

	if rv := atStmt.GetRelation(); rv != nil {
		fact.Table = rv.GetRelname()
	}

	cmds := atStmt.GetCmds()
	fact.CmdCount = len(cmds)

	if len(cmds) == 0 {
		t.Fatalf("%s: expected at least 1 AlterTableCmd, got 0", tc.name)
	}

	cmd := cmds[0].GetAlterTableCmd()
	if cmd == nil {
		t.Fatalf("%s: first cmd is not an AlterTableCmd", tc.name)
	}

	fact.SubtypeName = cmd.GetSubtype().String()
	fact.SubtypeNum = int32(cmd.GetSubtype())
	fact.CmdName = cmd.GetName()
	fact.HasDef = cmd.GetDef() != nil
	fact.CmdProto = cmd.String()

	if fact.HasDef {
		defNode := cmd.GetDef()
		fact.DefKind = strings.TrimPrefix(fmt.Sprintf("%T", defNode.GetNode()), "*pg_query.Node_")
		fact.DefProto = defNode.String()
	}

	return fact
}

func TestRemainingBoundaryASTCensus(t *testing.T) {
	t.Parallel()
	t.Log("")
	t.Log("=== PostgreSQL ALTER TABLE Remaining Boundary AST Census (7 unsupported_boundary) ===")
	t.Log("")

	t.Logf("%-20s %-40s | %-6s | %-15s | %-12s | %-22s | %-4s | %-6s | %-8s | %s",
		"Family", "Name", "Parse?", "TopKind", "Table", "Subtype", "Cmds", "CmdName", "HasDef", "DefKind")
	t.Log(strings.Repeat("-", 200))

	expectedShapes := map[string]struct {
		parseOK     bool
		topKind     string
		subtypeName string
		table       string
		hasDef      bool
	}{
		"SET EXPRESSION computed":              {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_SetExpression", table: "users", hasDef: true},
		"ADD GENERATED BY DEFAULT AS IDENTITY": {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_AddIdentity", table: "users", hasDef: true},
		"EXCLUDE USING gist":                   {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_AddConstraint", table: "bookings", hasDef: true},
		"ALTER CONSTRAINT DEFERRABLE":          {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_AlterConstraint", table: "orders", hasDef: true},
		"ALTER CONSTRAINT INITIALLY DEFERRED":  {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_AlterConstraint", table: "orders", hasDef: true},
		"SET WITHOUT OIDS":                     {parseOK: true, topKind: "AlterTableStmt", subtypeName: "AT_DropOids", table: "users", hasDef: false},
		"ALL IN TABLESPACE SET":                {parseOK: true, topKind: "AlterTableMoveAllStmt", subtypeName: "", table: "", hasDef: false},
	}

	for _, tc := range pgAlterTableRemainingBoundaryCases {
		fact := remainingBoundaryASTFactForCase(t, tc)

		t.Logf("%-20s %-40s | %-6v | %-15s | %-12s | %-22s | %-4d | %-6q | %-8v | %s",
			fact.Family, fact.Name, fact.ParseOK, fact.TopKind, fact.Table,
			fact.SubtypeName, fact.CmdCount, fact.CmdName, fact.HasDef, fact.DefKind)

		exp, ok := expectedShapes[tc.name]
		if !ok {
			t.Errorf("no expected shape for case %q", tc.name)
			continue
		}
		if fact.ParseOK != exp.parseOK {
			t.Errorf("case %q: parseOK = %v, want %v", tc.name, fact.ParseOK, exp.parseOK)
		}
		if fact.TopKind != exp.topKind {
			t.Errorf("case %q: topKind = %q, want %q", tc.name, fact.TopKind, exp.topKind)
		}
		if fact.SubtypeName != exp.subtypeName {
			if !fact.IsMoveAll {
				t.Errorf("case %q: subtype = %q, want %q", tc.name, fact.SubtypeName, exp.subtypeName)
			}
		}
		if !fact.IsMoveAll && fact.Table != exp.table {
			t.Errorf("case %q: table = %q, want %q", tc.name, fact.Table, exp.table)
		}
		if fact.HasDef != exp.hasDef {
			t.Errorf("case %q: hasDef = %v, want %v", tc.name, fact.HasDef, exp.hasDef)
		}
	}
}

func TestRemainingBoundaryASTDetail(t *testing.T) {
	t.Parallel()
	t.Log("")
	t.Log("=== Remaining Boundary AST Detail: def node inspection ===")
	t.Log("")

	for _, tc := range pgAlterTableRemainingBoundaryCases {
		tree, err := pg_query.Parse(tc.sql)
		if err != nil {
			t.Fatalf("%s: parse failed: %v", tc.name, err)
		}

		stmtNode := tree.GetStmts()[0].GetStmt().GetNode()

		t.Logf("--- %s [%s] ---", tc.name, tc.family)
		t.Logf("  SQL:     %s", tc.sql)

		if mv, ok := stmtNode.(*pg_query.Node_AlterTableMoveAllStmt); ok {
			mvStmt := mv.AlterTableMoveAllStmt
			t.Logf("  TopKind: AlterTableMoveAllStmt")
			t.Logf("  orig_tablespcname: %q", mvStmt.GetOrigTablespacename())
			t.Logf("  new_tablespcname:  %q", mvStmt.GetNewTablespacename())
			t.Logf("  objtype:           %s (%d)", mvStmt.GetObjtype().String(), int32(mvStmt.GetObjtype()))
			t.Log("")
			continue
		}

		atStmt := stmtNode.(*pg_query.Node_AlterTableStmt).AlterTableStmt
		cmd := atStmt.GetCmds()[0].GetAlterTableCmd()

		t.Logf("  Subtype: %s (%d)", cmd.GetSubtype().String(), int32(cmd.GetSubtype()))
		t.Logf("  CmdName: %q", cmd.GetName())
		t.Logf("  HasDef:  %v", cmd.GetDef() != nil)

		if cmd.GetDef() != nil {
			defNode := cmd.GetDef()
			defKind := strings.TrimPrefix(fmt.Sprintf("%T", defNode.GetNode()), "*pg_query.Node_")
			t.Logf("  DefKind: %s", defKind)

			switch d := defNode.GetNode().(type) {
			case *pg_query.Node_Constraint:
				c := d.Constraint
				t.Logf("  Constraint.contype:      %s (%d)", c.GetContype().String(), int32(c.GetContype()))
				t.Logf("  Constraint.conname:      %q", c.GetConname())
				t.Logf("  Constraint.raw_expr:     %v", c.GetRawExpr() != nil)
				t.Logf("  Constraint.indexname:    %q", c.GetIndexname())
				t.Logf("  Constraint.deferrable:   %v", c.GetDeferrable())
				t.Logf(" .Column.initdeferred:   %v", c.GetInitdeferred())
				t.Logf("  Constraint.access_method:%q", c.GetAccessMethod())
				t.Logf("  Constraint.options:      %v", c.GetOptions() != nil)
				t.Logf("  Constraint.where_clause: %v", c.GetWhereClause() != nil)
				t.Logf("  Constraint.pktable:      %v", c.GetPktable() != nil)
				t.Logf("  Constraint.keys len:     %d", len(c.GetKeys()))
				t.Logf("  Constraint.exclusions len:%d", len(c.GetExclusions()))
			default:
				// Log raw proto for any def node kind not explicitly handled above.
				t.Logf("  Def node kind=%s (raw): %s", defKind, defNode.String())
			}
		}

		// Log identity fields
		t.Logf("  --- identity fields ---")
		t.Logf("  Relation.relname:  %q", atStmt.GetRelation().GetRelname())
		t.Logf("  Relation.schemaname: %q", atStmt.GetRelation().GetSchemaname())
		t.Logf("  cmd.GetName():     %q", cmd.GetName())
		t.Logf("  cmd.missing_ok:    %v", cmd.GetMissingOk())

		// Check for payload risk fields
		t.Logf("  --- payload risk ---")
		t.Logf("  cmd.newowner:      %v", cmd.GetNewowner() != nil)
		t.Logf("  cmd.behavior:      %s", cmd.GetBehavior().String())

		t.Log("")
	}
}

func TestRemainingBoundaryIdentityExtraction(t *testing.T) {
	t.Parallel()
	t.Log("")
	t.Log("=== Remaining Boundary Identity Extraction ===")
	t.Log("")

	type identityResult struct {
		name       string
		family     string
		table      string
		column     string
		constraint string
		tablespace string
		index      string
	}

	t.Logf("%-40s | %-20s | %-12s | %-12s | %-20s | %-12s | %-12s",
		"Name", "Family", "Table", "Column", "Constraint", "Tablespace", "Index")
	t.Log(strings.Repeat("-", 160))

	for _, tc := range pgAlterTableRemainingBoundaryCases {
		tree, err := pg_query.Parse(tc.sql)
		if err != nil {
			t.Fatalf("%s: parse failed: %v", tc.name, err)
		}

		stmtNode := tree.GetStmts()[0].GetStmt().GetNode()

		ir := identityResult{
			name:   tc.name,
			family: tc.family,
		}

		if mv, ok := stmtNode.(*pg_query.Node_AlterTableMoveAllStmt); ok {
			mvStmt := mv.AlterTableMoveAllStmt
			ir.tablespace = fmt.Sprintf("%s -> %s", mvStmt.GetOrigTablespacename(), mvStmt.GetNewTablespacename())
		} else {
			atStmt := stmtNode.(*pg_query.Node_AlterTableStmt).AlterTableStmt
			cmd := atStmt.GetCmds()[0].GetAlterTableCmd()
			ir.table = atStmt.GetRelation().GetRelname()
			ir.column = cmd.GetName()

			if cmd.GetDef() != nil {
				switch d := cmd.GetDef().GetNode().(type) {
				case *pg_query.Node_Constraint:
					ir.constraint = d.Constraint.GetConname()
					ir.index = d.Constraint.GetIndexname()
				}
			}
		}

		t.Logf("%-40s | %-20s | %-12s | %-12s | %-20s | %-12s | %-12s",
			ir.name, ir.family, ir.table, ir.column, ir.constraint, ir.tablespace, ir.index)
	}
}

func TestRemainingBoundarySubtypeNumericValues(t *testing.T) {
	t.Parallel()
	t.Log("")
	t.Log("=== Remaining Boundary Subtype Numeric Values ===")
	t.Log("")

	t.Logf("%-40s | %-25s | %-8s", "Name", "Subtype", "Numeric")
	t.Log(strings.Repeat("-", 80))

	for _, tc := range pgAlterTableRemainingBoundaryCases {
		tree, err := pg_query.Parse(tc.sql)
		if err != nil {
			t.Fatalf("%s: parse failed: %v", tc.name, err)
		}

		stmtNode := tree.GetStmts()[0].GetStmt().GetNode()

		if mv, ok := stmtNode.(*pg_query.Node_AlterTableMoveAllStmt); ok {
			mvStmt := mv.AlterTableMoveAllStmt
			t.Logf("%-40s | %-25s | objtype=%d orig=%q new=%q",
				tc.name, "AlterTableMoveAllStmt", int32(mvStmt.GetObjtype()), mvStmt.GetOrigTablespacename(), mvStmt.GetNewTablespacename())
			continue
		}

		cmd := stmtNode.(*pg_query.Node_AlterTableStmt).AlterTableStmt.GetCmds()[0].GetAlterTableCmd()
		subtype := cmd.GetSubtype()
		t.Logf("%-40s | %-25s | %-8d", tc.name, subtype.String(), int32(subtype))
	}
}
