//go:build postgresql

package postgresql

import (
	"fmt"
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
	pg_query "github.com/pganalyze/pg_query_go/v6"
)

func TestExtractAlterTableAddGeneratedStoredColumnIsSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	if statement.DDL.Alter[0].Action != "add_column" {
		t.Fatalf("expected action add_column, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.Definition == nil {
		t.Fatal("expected alter column definition")
	}
	if statement.DDL.Alter[0].Column.Definition.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a, got %q", statement.DDL.Alter[0].Column.Definition.GeneratedWhen)
	}
}

func TestExtractAlterTableAddIdentityColumnIsSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	if statement.DDL.Alter[0].Action != "add_column" {
		t.Fatalf("expected action add_column, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.Definition == nil {
		t.Fatal("expected alter column definition")
	}
	if statement.DDL.Alter[0].Column.Definition.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a, got %q", statement.DDL.Alter[0].Column.Definition.GeneratedWhen)
	}
	if !statement.DDL.Alter[0].Column.Definition.IsIdentity {
		t.Fatal("expected is_identity=true")
	}
}

func TestExtractAlterTableDropGeneratedExpressionNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
  ALTER COLUMN full_name DROP EXPRESSION;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table DDL, got %v", statement.DDL)
	}
	if len(statement.DDL.Alter) == 0 || statement.DDL.Alter[0].Action != "drop_expression" {
		t.Fatalf("expected action drop_expression, got %v", statement.DDL.Alter)
	}
}

func TestExtractAlterTableSetIdentityGeneratedNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
  ALTER COLUMN id SET GENERATED BY DEFAULT;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table DDL, got %v", statement.DDL)
	}
	if len(statement.DDL.Alter) == 0 || statement.DDL.Alter[0].Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %v", statement.DDL.Alter)
	}
	if statement.DDL.Alter[0].Options["generated_when"] != "d" {
		t.Fatalf("expected generated_when=d, got %v", statement.DDL.Alter[0].Options)
	}
}

func TestExtractAlterTableSetIdentityGeneratedAlwaysNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
  ALTER COLUMN id SET GENERATED ALWAYS;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table DDL, got %v", statement.DDL)
	}
	if len(statement.DDL.Alter) == 0 || statement.DDL.Alter[0].Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %v", statement.DDL.Alter)
	}
	if statement.DDL.Alter[0].Options["generated_when"] != "a" {
		t.Fatalf("expected generated_when=a, got %v", statement.DDL.Alter[0].Options)
	}
}

func TestExtractAlterTableDropIdentityNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
  ALTER COLUMN id DROP IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table DDL, got %v", statement.DDL)
	}
	if len(statement.DDL.Alter) == 0 || statement.DDL.Alter[0].Action != "drop_identity" {
		t.Fatalf("expected action drop_identity, got %v", statement.DDL.Alter)
	}
}

func TestParseCreateTableExclusionConstraintAST(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE bookings (
  room_id int,
  during tsrange,
  EXCLUDE USING gist (room_id WITH =, during WITH &&)
);`

	stmt := parseCreateStmtAST(t, sql)

	elts := stmt.GetTableElts()
	if len(elts) != 3 {
		t.Fatalf("expected 3 table elements, got %d", len(elts))
	}

	// Third element should be the EXCLUDE constraint (a table-level constraint).
	constraintNode := elts[2].GetConstraint()
	if constraintNode == nil {
		t.Fatal("third table element is not a Constraint node")
	}

	// FACT 1: The exclusion constraint has contype CONSTR_EXCLUSION (9).
	contype := constraintNode.GetContype()
	t.Logf("Constraint.Contype = %s (%d)", contype.String(), contype)
	if contype != pg_query.ConstrType_CONSTR_EXCLUSION {
		t.Fatalf("expected CONSTR_EXCLUSION, got %s (%d)", contype.String(), contype)
	}

	// FACT 2: The access method ("gist") is stored in Constraint.AccessMethod.
	accessMethod := constraintNode.GetAccessMethod()
	t.Logf("Constraint.AccessMethod = %q", accessMethod)
	if accessMethod != "gist" {
		t.Fatalf("expected access method 'gist', got %q", accessMethod)
	}

	// FACT 3: The exclusion elements are stored in Constraint.Exclusions.
	exclusions := constraintNode.GetExclusions()
	t.Logf("Constraint.Exclusions count = %d", len(exclusions))
	if len(exclusions) == 0 {
		t.Fatal("expected non-empty Exclusions list for EXCLUDE constraint")
	}

	// FACT 4: The constraint name is empty (unnamed exclusion constraint).
	conname := constraintNode.GetConname()
	t.Logf("Constraint.Conname = %q", conname)

	// FACT 5: Verify the exclusion constraint has no FK/PK related fields populated.
	if constraintNode.GetFkAttrs() != nil {
		t.Log("Constraint.FkAttrs is populated (unexpected for EXCLUSION)")
	}
}

func TestParseCreateTablePartitionByAST(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE events (
  id bigint,
  created_at timestamptz NOT NULL
) PARTITION BY RANGE (created_at);`

	stmt := parseCreateStmtAST(t, sql)

	// FACT 1: CreateStmt.Partspec is non-nil for PARTITION BY.
	partspec := stmt.GetPartspec()
	t.Logf("CreateStmt.Partspec != nil: %v", partspec != nil)
	if partspec == nil {
		t.Fatal("expected CreateStmt.Partspec to be non-nil for PARTITION BY RANGE")
	}

	// FACT 2: The partition strategy is RANGE (PartitionStrategy_PARTITION_STRATEGY_RANGE = 2).
	strategy := partspec.GetStrategy()
	t.Logf("PartitionSpec.Strategy = %s (%d)", strategy.String(), strategy)
	if strategy != pg_query.PartitionStrategy_PARTITION_STRATEGY_RANGE {
		t.Fatalf("expected PARTITION_STRATEGY_RANGE, got %s (%d)", strategy.String(), strategy)
	}

	// FACT 3: PartitionSpec.PartParams contains the partition key columns.
	partParams := partspec.GetPartParams()
	t.Logf("PartitionSpec.PartParams count = %d", len(partParams))
	if len(partParams) == 0 {
		t.Fatal("expected non-empty PartParams for PARTITION BY RANGE")
	}

	// FACT 4: CreateStmt.Partbound should be nil for a top-level partitioned table
	// (Partbound is used when attaching a partition, not when declaring the parent).
	partbound := stmt.GetPartbound()
	t.Logf("CreateStmt.Partbound != nil: %v", partbound != nil)
	if partbound != nil {
		t.Log("CreateStmt.Partbound is non-nil — this is unexpected for a partitioned parent table")
	}

	// FACT 5: TableElts should still contain the regular column definitions.
	elts := stmt.GetTableElts()
	if len(elts) != 2 {
		t.Fatalf("expected 2 table elements, got %d", len(elts))
	}
}

// ---------------------------------------------------------------------------
// v0.27.0 Task 1: Schema-qualified REFERENCES characterization tests
// ---------------------------------------------------------------------------
// These tests prove three things:
//  1. pg_query.RangeVar carries both Schemaname and Relname for schema-qualified
//     REFERENCES (inline and table-level).
//  2. The current extractor drops schema because rangeVarName() only returns
//     Relname — this is an extractor design choice, not an AST limitation.
//  3. Adding ReferencedSchema to spec.Constraint would be a pure additive change.
//
// No production code is modified. These are decision-gate tests.
// ---------------------------------------------------------------------------

func TestParseCreateTableInlineSchemaQualifiedReferencesAST(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint REFERENCES public.users(id)
);`

	stmt := parseCreateStmtAST(t, sql)

	elts := stmt.GetTableElts()
	if len(elts) != 2 {
		t.Fatalf("expected 2 table elements, got %d", len(elts))
	}

	// Second element is the user_id column with inline REFERENCES.
	colDef := elts[1].GetColumnDef()
	if colDef == nil {
		t.Fatal("expected second table element to be a ColumnDef")
	}
	if colDef.GetColname() != "user_id" {
		t.Fatalf("expected column name user_id, got %q", colDef.GetColname())
	}

	// ColumnDef should have exactly one constraint (the REFERENCES).
	colConstraints := colDef.GetConstraints()
	if len(colConstraints) != 1 {
		t.Fatalf("expected 1 column constraint, got %d", len(colConstraints))
	}
	constraint := colConstraints[0].GetConstraint()
	if constraint == nil {
		t.Fatal("expected Constraint node")
	}
	if constraint.GetContype() != pg_query.ConstrType_CONSTR_FOREIGN {
		t.Fatalf("expected CONSTR_FOREIGN, got %s", constraint.GetContype())
	}

	// FACT 1: Pktable (the referenced table) is a RangeVar that carries
	// both Schemaname and Relname for schema-qualified references.
	pkTable := constraint.GetPktable()
	if pkTable == nil {
		t.Fatal("expected non-nil Pktable (RangeVar)")
	}
	schemaName := pkTable.GetSchemaname()
	relName := pkTable.GetRelname()

	t.Logf("Inline REFERENCES Pktable.Schemaname = %q", schemaName)
	t.Logf("Inline REFERENCES Pktable.Relname    = %q", relName)

	if schemaName != "public" {
		t.Fatalf("expected Pktable.Schemaname %q, got %q — AST does expose schema for inline REFERENCES", "public", schemaName)
	}
	if relName != "users" {
		t.Fatalf("expected Pktable.Relname %q, got %q", "users", relName)
	}

	// FACT 2: PkAttrs carries the referenced column name.
	pkAttrs := constraint.GetPkAttrs()
	if len(pkAttrs) != 1 {
		t.Fatalf("expected 1 pk_attr, got %d", len(pkAttrs))
	}
	if stringNodeValue(pkAttrs[0]) != "id" {
		t.Fatalf("expected pk_attr id, got %q", stringNodeValue(pkAttrs[0]))
	}
}

func TestParseCreateTableTableLevelSchemaQualifiedForeignKeyAST(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);`

	stmt := parseCreateStmtAST(t, sql)

	elts := stmt.GetTableElts()
	if len(elts) != 3 {
		t.Fatalf("expected 3 table elements, got %d", len(elts))
	}

	// Third element is the named table-level CONSTRAINT.
	constraintNode := elts[2].GetConstraint()
	if constraintNode == nil {
		t.Fatal("expected third table element to be a Constraint")
	}
	if constraintNode.GetConname() != "fk_orders_user" {
		t.Fatalf("expected constraint name fk_orders_user, got %q", constraintNode.GetConname())
	}
	if constraintNode.GetContype() != pg_query.ConstrType_CONSTR_FOREIGN {
		t.Fatalf("expected CONSTR_FOREIGN, got %s", constraintNode.GetContype())
	}

	// FACT 1: Pktable carries schema for table-level FK too.
	pkTable := constraintNode.GetPktable()
	if pkTable == nil {
		t.Fatal("expected non-nil Pktable (RangeVar)")
	}
	schemaName := pkTable.GetSchemaname()
	relName := pkTable.GetRelname()

	t.Logf("Table-level FK Pktable.Schemaname = %q", schemaName)
	t.Logf("Table-level FK Pktable.Relname    = %q", relName)

	if schemaName != "public" {
		t.Fatalf("expected Pktable.Schemaname %q, got %q — AST exposes schema for table-level FK too", "public", schemaName)
	}
	if relName != "users" {
		t.Fatalf("expected Pktable.Relname %q, got %q", "users", relName)
	}

	// FACT 2: FkAttrs and PkAttrs are populated correctly.
	fkAttrs := constraintNode.GetFkAttrs()
	if len(fkAttrs) != 1 || stringNodeValue(fkAttrs[0]) != "user_id" {
		t.Fatalf("expected fk_attrs [user_id], got %#v", fkAttrs)
	}
	pkAttrs := constraintNode.GetPkAttrs()
	if len(pkAttrs) != 1 || stringNodeValue(pkAttrs[0]) != "id" {
		t.Fatalf("expected pk_attrs [id], got %#v", pkAttrs)
	}
}

func TestExtractCreateTableInlineSchemaQualifiedReferencesDropsSchemaToday(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint REFERENCES public.users(id)
);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind %q, got %q", spec.KindDDL, statement.Kind)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported create table, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d", len(statement.DDL.Constraints))
	}

	constraint := statement.DDL.Constraints[0]

	// FACT: The extractor currently preserves the bare table name.
	if constraint.ReferencedTable != "users" {
		t.Fatalf("expected ReferencedTable %q, got %q", "users", constraint.ReferencedTable)
	}
	if len(constraint.ReferencedColumns) != 1 || constraint.ReferencedColumns[0] != "id" {
		t.Fatalf("expected ReferencedColumns [id], got %#v", constraint.ReferencedColumns)
	}

	// FACT: The spec.Constraint struct has no ReferencedSchema field today.
	// This test documents the current gap: schema "public" is available in the
	// AST (proven by TestParseCreateTableInlineSchemaQualifiedReferencesAST)
	// but is silently discarded by rangeVarName() which only returns Relname.
	//
	// Once ReferencedSchema is added, this test should be updated to assert:
	//   constraint.ReferencedSchema == "public"
	t.Logf("Current behavior: ReferencedTable=%q, schema info is lost", constraint.ReferencedTable)
	t.Log("Gap confirmed: pg_query.RangeVar has Schemaname=public but extractor drops it via rangeVarName()")
}

func TestExtractCreateTableTableLevelSchemaQualifiedForeignKeyDropsSchemaToday(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind %q, got %q", spec.KindDDL, statement.Kind)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported create table, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d", len(statement.DDL.Constraints))
	}

	constraint := statement.DDL.Constraints[0]
	if constraint.Type != "foreign_key" || constraint.Name != "fk_orders_user" {
		t.Fatalf("expected named foreign_key constraint, got %+v", constraint)
	}

	// FACT: The extractor currently preserves the bare table name.
	if constraint.ReferencedTable != "users" {
		t.Fatalf("expected ReferencedTable %q, got %q", "users", constraint.ReferencedTable)
	}
	if len(constraint.ReferencedColumns) != 1 || constraint.ReferencedColumns[0] != "id" {
		t.Fatalf("expected ReferencedColumns [id], got %#v", constraint.ReferencedColumns)
	}

	// FACT: Same gap as inline case — schema is available in AST but discarded.
	// Both applyTableConstraint and applyColumnConstraints use rangeVarName()
	// which only extracts Relname, not Schemaname.
	t.Logf("Current behavior: ReferencedTable=%q, schema info is lost", constraint.ReferencedTable)
	t.Log("Gap confirmed: applies to both inline REFERENCES and table-level FOREIGN KEY")
}

// ---------------------------------------------------------------------------
// v0.27.0 Task 2: Behavior tests — schema-qualified REFERENCES preservation
// ---------------------------------------------------------------------------
// These tests assert that the extractor preserves schema-qualified reference
// semantics via the new ReferencedSchema field on spec.Constraint.
// ---------------------------------------------------------------------------

func TestExtractCreateTableInlineSchemaQualifiedReferencesPreservesReferencedSchema(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint REFERENCES public.users(id)
);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind %q, got %q", spec.KindDDL, statement.Kind)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported create table, got unsupported %#v", statement.Unsupported)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationCreateTable {
		t.Fatalf("expected create_table ddl payload, got %#v", statement.DDL)
	}
	if len(statement.DDL.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d", len(statement.DDL.Constraints))
	}

	constraint := statement.DDL.Constraints[0]
	if constraint.Type != "foreign_key" {
		t.Fatalf("expected foreign_key constraint, got %+v", constraint)
	}
	if constraint.ReferencedSchema != "public" {
		t.Fatalf("expected ReferencedSchema %q, got %q", "public", constraint.ReferencedSchema)
	}
	if constraint.ReferencedTable != "users" {
		t.Fatalf("expected ReferencedTable %q, got %q", "users", constraint.ReferencedTable)
	}
	if len(constraint.ReferencedColumns) != 1 || constraint.ReferencedColumns[0] != "id" {
		t.Fatalf("expected ReferencedColumns [id], got %#v", constraint.ReferencedColumns)
	}
}

func TestExtractCreateTableTableLevelSchemaQualifiedForeignKeyPreservesReferencedSchema(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE orders (
  id bigint PRIMARY KEY,
  user_id bigint,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind %q, got %q", spec.KindDDL, statement.Kind)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported create table, got unsupported %#v", statement.Unsupported)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationCreateTable {
		t.Fatalf("expected create_table ddl payload, got %#v", statement.DDL)
	}
	if len(statement.DDL.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d", len(statement.DDL.Constraints))
	}

	constraint := statement.DDL.Constraints[0]
	if constraint.Type != "foreign_key" || constraint.Name != "fk_orders_user" {
		t.Fatalf("expected named foreign_key constraint, got %+v", constraint)
	}
	if constraint.ReferencedSchema != "public" {
		t.Fatalf("expected ReferencedSchema %q, got %q", "public", constraint.ReferencedSchema)
	}
	if constraint.ReferencedTable != "users" {
		t.Fatalf("expected ReferencedTable %q, got %q", "users", constraint.ReferencedTable)
	}
	if len(constraint.ReferencedColumns) != 1 || constraint.ReferencedColumns[0] != "id" {
		t.Fatalf("expected ReferencedColumns [id], got %#v", constraint.ReferencedColumns)
	}
}

// ---------------------------------------------------------------------------
// v0.33.0 Task 1: Generated expression and identity option characterization
// ---------------------------------------------------------------------------

func TestParsePostgreSQLGeneratedExpressionSupportReadinessFacts(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
  first_name text,
  last_name text,
  full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED
);`

	stmt := parseCreateStmtAST(t, sql)

	elts := stmt.GetTableElts()
	if len(elts) != 3 {
		t.Fatalf("expected 3 table elements, got %d", len(elts))
	}

	// FACT 1: AST is CreateStmt (confirmed by parseCreateStmtAST helper).

	// FACT 2: Find full_name ColumnDef.
	colNode := elts[2].GetColumnDef()
	if colNode == nil {
		t.Fatal("third table element is not a ColumnDef")
	}
	if colNode.GetColname() != "full_name" {
		t.Fatalf("expected column name 'full_name', got %q", colNode.GetColname())
	}

	// FACT 3: Find CONSTR_GENERATED.
	constraints := colNode.GetConstraints()
	var generatedConstraint *pg_query.Constraint
	for _, c := range constraints {
		con := c.GetConstraint()
		if con != nil && con.GetContype() == pg_query.ConstrType_CONSTR_GENERATED {
			generatedConstraint = con
			break
		}
	}
	if generatedConstraint == nil {
		t.Fatal("expected CONSTR_GENERATED in column constraint list")
	}

	// FACT 4: GeneratedWhen == "a" (ALWAYS).
	if generatedConstraint.GetGeneratedWhen() != "a" {
		t.Fatalf("expected GeneratedWhen='a', got %q", generatedConstraint.GetGeneratedWhen())
	}

	// FACT 5: RawExpr != nil.
	rawExpr := generatedConstraint.GetRawExpr()
	if rawExpr == nil {
		t.Fatal("expected CONSTR_GENERATED.RawExpr to be non-nil")
	}

	// FACT 6: RawExpr top-level node type.
	t.Logf("RawExpr node type: %T", rawExpr.GetNode())

	// Walk the expression tree to find column refs and string literals.
	var columnRefs []string
	var stringLiterals []string
	walkExprForStrings(t, rawExpr, &columnRefs, &stringLiterals)

	t.Logf("Column refs found in RawExpr: %v", columnRefs)
	t.Logf("String literals found in RawExpr: %v", stringLiterals)

	// FACT 7: Can stably see first_name in the expression.
	foundFirstName := false
	for _, ref := range columnRefs {
		if ref == "first_name" {
			foundFirstName = true
		}
	}
	if !foundFirstName {
		t.Fatal("expected to find 'first_name' column reference in RawExpr")
	}

	// FACT 8: Can stably see last_name in the expression.
	foundLastName := false
	for _, ref := range columnRefs {
		if ref == "last_name" {
			foundLastName = true
		}
	}
	if !foundLastName {
		t.Fatal("expected to find 'last_name' column reference in RawExpr")
	}

	// FACT 9: Can stably see the string space literal.
	foundSpaceLiteral := false
	for _, lit := range stringLiterals {
		if lit == " " {
			foundSpaceLiteral = true
		}
	}
	if !foundSpaceLiteral {
		t.Fatal("expected to find ' ' string literal in RawExpr")
	}

	// FACT 10: pg_query does not expose DeparseExpr. Only pg_query.Deparse
	// operates on a full ParseResult. There is no stable per-expression
	// deparse helper in pg_query_go/v6. This means GeneratedExpression
	// requires a custom renderer or defer.
	t.Log("pg_query has no DeparseExpr - GeneratedExpression MUST use custom renderer or defer")
	// FACT 10: Record whether pg_query.DeparseExpr can render the expression.
}

// walkExprForStrings recursively walks a pg_query Node tree to extract
// ColumnRef names and A_Const string values for characterization.
func walkExprForStrings(t *testing.T, node *pg_query.Node, columnRefs *[]string, stringLiterals *[]string) {
	t.Helper()
	if node == nil {
		return
	}

	if colRef := node.GetColumnRef(); colRef != nil {
		for _, field := range colRef.GetFields() {
			if str := field.GetString_(); str != nil {
				*columnRefs = append(*columnRefs, str.GetSval())
			}
		}
		return
	}

	if aConst := node.GetAConst(); aConst != nil {
		if str := aConst.GetSval(); str != nil {
			*stringLiterals = append(*stringLiterals, str.GetSval())
		}
		return
	}

	if aExpr := node.GetAExpr(); aExpr != nil {
		walkExprForStrings(t, aExpr.GetLexpr(), columnRefs, stringLiterals)
		walkExprForStrings(t, aExpr.GetRexpr(), columnRefs, stringLiterals)
		return
	}

	if funcCall := node.GetFuncCall(); funcCall != nil {
		for _, fn := range funcCall.GetFuncname() {
			walkExprForStrings(t, fn, columnRefs, stringLiterals)
		}
		for _, arg := range funcCall.GetArgs() {
			walkExprForStrings(t, arg, columnRefs, stringLiterals)
		}
		return
	}

	if list := node.GetList(); list != nil {
		for _, item := range list.GetItems() {
			walkExprForStrings(t, item, columnRefs, stringLiterals)
		}
		return
	}
}

func TestParsePostgreSQLIdentityOptionSupportReadinessFacts(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY (
    START WITH 10
    INCREMENT BY 5
    MINVALUE 1
    MAXVALUE 9999
    CACHE 20
    CYCLE
  ) PRIMARY KEY
);`

	stmt := parseCreateStmtAST(t, sql)

	elts := stmt.GetTableElts()
	if len(elts) != 1 {
		t.Fatalf("expected 1 table element, got %d", len(elts))
	}

	// FACT 1: Find id ColumnDef.
	colNode := elts[0].GetColumnDef()
	if colNode == nil {
		t.Fatal("first table element is not a ColumnDef")
	}
	if colNode.GetColname() != "id" {
		t.Fatalf("expected column name 'id', got %q", colNode.GetColname())
	}

	// FACT 2: Find CONSTR_IDENTITY.
	constraints := colNode.GetConstraints()
	var identityConstraint *pg_query.Constraint
	for _, c := range constraints {
		con := c.GetConstraint()
		if con != nil && con.GetContype() == pg_query.ConstrType_CONSTR_IDENTITY {
			identityConstraint = con
			break
		}
	}
	if identityConstraint == nil {
		t.Fatal("expected CONSTR_IDENTITY in column constraint list")
	}

	// FACT 3: GeneratedWhen == "d" (BY DEFAULT).
	if identityConstraint.GetGeneratedWhen() != "d" {
		t.Fatalf("expected GeneratedWhen='d' for BY DEFAULT, got %q", identityConstraint.GetGeneratedWhen())
	}

	// FACT 4: Options is non-empty.
	options := identityConstraint.GetOptions()
	if len(options) == 0 {
		t.Fatal("expected identity constraint to have options")
	}

	// FACT 5: Extract all option keys and values.
	optionValues := make(map[string]interface{})
	for _, opt := range options {
		defElem := opt.GetDefElem()
		if defElem == nil {
			t.Fatal("expected identity option to be a DefElem")
		}
		name := defElem.GetDefname()
		argNode := defElem.GetArg()

		if argNode == nil {
			optionValues[name] = nil
			t.Logf("Option %q = nil (no arg node)", name)
			continue
		}

		if intNode := argNode.GetInteger(); intNode != nil {
			optionValues[name] = intNode.GetIval()
			t.Logf("Option %q = %d (Integer)", name, intNode.GetIval())
			continue
		}

		if floatNode := argNode.GetFloat(); floatNode != nil {
			optionValues[name] = floatNode.GetFval()
			t.Logf("Option %q = %q (Float string)", name, floatNode.GetFval())
			continue
		}

		if strNode := argNode.GetString_(); strNode != nil {
			optionValues[name] = strNode.GetSval()
			t.Logf("Option %q = %q (String)", name, strNode.GetSval())
			continue
		}

		// Try Boolean (used by CYCLE / NO CYCLE).
		if boolNode := argNode.GetBoolean(); boolNode != nil {
			optionValues[name] = boolNode.GetBoolval()
			t.Logf("Option %q = %v (Boolean)", name, boolNode.GetBoolval())
			continue
		}

		optionValues[name] = fmt.Sprintf("UNKNOWN_TYPE:%T", argNode.GetNode())
		t.Logf("Option %q = unknown type %T", name, argNode.GetNode())
	}

	// FACT 6: Option keys include start, increment, minvalue, maxvalue, cache, cycle.
	requiredKeys := []string{"start", "increment", "minvalue", "maxvalue", "cache", "cycle"}
	for _, key := range requiredKeys {
		if _, ok := optionValues[key]; !ok {
			t.Fatalf("expected option key %q in identity options, got keys: %v", key, optionKeys(optionValues))
		}
	}

	// FACT 7: Numeric options have integer values.
	assertIntOption(t, optionValues, "start", 10)
	assertIntOption(t, optionValues, "increment", 5)
	assertIntOption(t, optionValues, "minvalue", 1)
	assertIntOption(t, optionValues, "maxvalue", 9999)
	assertIntOption(t, optionValues, "cache", 20)

	// FACT 8: Cycle option shape.
	cycleVal := optionValues["cycle"]
	t.Logf("CYCLE option value: %v (type: %T)", cycleVal, cycleVal)

	switch v := cycleVal.(type) {
	case nil:
		t.Logf("CYCLE is a flag (no arg) - boolean-safe: false, flag-style: true")
	case bool:
		t.Logf("CYCLE is boolean %v - boolean-safe, can enter IdentityOptions", v)
		if !v {
			t.Fatal("expected CYCLE to be true")
		}
	case int32:
		t.Logf("CYCLE is integer %d - boolean-safe if 0/1", v)
	case string:
		t.Logf("CYCLE is string %q - needs normalization", v)
	default:
		t.Logf("CYCLE is unexpected type %T: %v", v, v)
	}
}

func assertIntOption(t *testing.T, options map[string]interface{}, key string, expected int32) {
	t.Helper()
	val, ok := options[key]
	if !ok {
		t.Fatalf("expected option %q to exist", key)
	}
	intVal, ok := val.(int32)
	if !ok {
		t.Fatalf("expected option %q to be int32, got %T: %v", key, val, val)
	}
	if intVal != expected {
		t.Fatalf("expected option %q = %d, got %d", key, expected, intVal)
	}
}

func optionKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}

// ---------------------------------------------------------------------------
// v0.33.0 Task 2: Extractor behavior tests — generated/identity fact preservation
// ---------------------------------------------------------------------------
// These tests assert that the extractor preserves GeneratedWhen, IsIdentity,
// IdentityOptions on spec.Column and surfaces Metadata on UnsupportedDetail.
// ---------------------------------------------------------------------------
