//go:build postgresql

package postgresql

import (
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
	pg_query "github.com/pganalyze/pg_query_go/v6"
)

func TestExtractCreateTableGeneratedStoredPreservesGeneratedWhen(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  first_name text,
	  last_name text,
	  full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED
	);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "full_name" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column full_name in DDL.Columns")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a, got %q", col.GeneratedWhen)
	}
}

func TestExtractCreateTableIdentityColumnPreservesMetadataWithOptions(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  id bigint GENERATED BY DEFAULT AS IDENTITY (
	    START WITH 10
	    INCREMENT BY 5
	    MINVALUE 1
	    MAXVALUE 9999
	    CACHE 20
	    CYCLE
	  ) PRIMARY KEY
	);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "id" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column id in DDL.Columns")
	}
	if col.GeneratedWhen != "d" {
		t.Fatalf("expected generated_when=d, got %q", col.GeneratedWhen)
	}
	if !col.IsIdentity {
		t.Fatal("expected is_identity=true")
	}
	opts := col.IdentityOptions
	if opts == nil {
		t.Fatal("expected identity_options to be populated")
	}
	if opts["start"] != int32(10) {
		t.Fatalf("expected start=10, got %v", opts["start"])
	}
	if opts["increment"] != int32(5) {
		t.Fatalf("expected increment=5, got %v", opts["increment"])
	}
	if opts["cycle"] != true {
		t.Fatalf("expected cycle=true, got %v", opts["cycle"])
	}
}

func TestExtractAlterTableAddIdentityColumnPreservesMetadata(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	col := statement.DDL.Alter[0].Column.Definition
	if col == nil {
		t.Fatal("expected alter column definition")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a, got %q", col.GeneratedWhen)
	}
	if !col.IsIdentity {
		t.Fatal("expected is_identity=true")
	}
}

func TestExtractAlterTableAddGeneratedStoredPreservesMetadata(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	col := statement.DDL.Alter[0].Column.Definition
	if col == nil {
		t.Fatal("expected alter column definition")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a, got %q", col.GeneratedWhen)
	}
}

// ---------------------------------------------------------------------------
// v0.34.0 Task 1: Characterization tests — facts before support admission
// ---------------------------------------------------------------------------
// These tests prove that generated/identity facts are already stable in the
// current unsupported path. Support admission (Task 2) only needs to remove
// the explicit rejection; facts already flow through Unsupported.Metadata
// and are ready to land on spec.Column via columnFromDef once the gate opens.

func TestExtractCreateTableGeneratedStoredNowSupported(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  first_name text,
	  last_name text,
	  full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED
	);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "full_name" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column full_name in DDL.Columns")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", col.GeneratedWhen)
	}
}

func TestExtractCreateTableIdentityNowSupported(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  id bigint GENERATED BY DEFAULT AS IDENTITY (
	    START WITH 10
	    INCREMENT BY 5
	    MINVALUE 1
	    MAXVALUE 9999
	    CACHE 20
	    CYCLE
	  ) PRIMARY KEY
	);`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "id" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column id in DDL.Columns")
	}
	if col.GeneratedWhen != "d" {
		t.Fatalf("expected generated_when=d (BY DEFAULT), got %q", col.GeneratedWhen)
	}
	if !col.IsIdentity {
		t.Fatal("expected is_identity=true")
	}
	opts := col.IdentityOptions
	if opts == nil {
		t.Fatal("expected identity_options")
	}
	if opts["start"] != int32(10) {
		t.Fatalf("expected start=10, got %v", opts["start"])
	}
	if opts["increment"] != int32(5) {
		t.Fatalf("expected increment=5, got %v", opts["increment"])
	}
	if opts["minvalue"] != int32(1) {
		t.Fatalf("expected minvalue=1, got %v", opts["minvalue"])
	}
	if opts["maxvalue"] != int32(9999) {
		t.Fatalf("expected maxvalue=9999, got %v", opts["maxvalue"])
	}
	if opts["cache"] != int32(20) {
		t.Fatalf("expected cache=20, got %v", opts["cache"])
	}
	if opts["cycle"] != true {
		t.Fatalf("expected cycle=true, got %v", opts["cycle"])
	}
}

func TestExtractAlterTableAddGeneratedStoredNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	col := statement.DDL.Alter[0].Column.Definition
	if col == nil {
		t.Fatal("expected alter column definition")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", col.GeneratedWhen)
	}
}

func TestExtractAlterTableAddIdentityNowSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q", statement.Unsupported.Feature)
	}
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter action")
	}
	col := statement.DDL.Alter[0].Column.Definition
	if col == nil {
		t.Fatal("expected alter column definition")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", col.GeneratedWhen)
	}
	if !col.IsIdentity {
		t.Fatal("expected is_identity=true")
	}
}

// ---------------------------------------------------------------------------
// v0.34.0 Task 2: Narrow support admission tests
// ---------------------------------------------------------------------------
// These tests assert that the narrow generated/identity definition forms are
// now supported (no unsupported detail) and that facts land on spec.Column.

func TestExtractCreateTableGeneratedStoredBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  first_name text,
	  last_name text,
	  full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED
	);`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement/DDL payload is valid.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationCreateTable {
		t.Fatalf("expected operation create_table, got %q", statement.DDL.Operation)
	}

	// C. Facts preserved on spec.Column.
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "full_name" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column full_name in DDL.Columns")
	}
	if col.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", col.GeneratedWhen)
	}
	if col.IsIdentity {
		t.Fatal("expected is_identity=false for generated stored column")
	}
}

func TestExtractCreateTableIdentityBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `CREATE TABLE users (
	  id bigint GENERATED BY DEFAULT AS IDENTITY (
	    START WITH 10
	    INCREMENT BY 5
	    MINVALUE 1
	    MAXVALUE 9999
	    CACHE 20
	    CYCLE
	  ) PRIMARY KEY
	);`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement/DDL payload is valid.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationCreateTable {
		t.Fatalf("expected operation create_table, got %q", statement.DDL.Operation)
	}

	// C. Facts preserved on spec.Column.
	var col *spec.Column
	for i := range statement.DDL.Columns {
		if statement.DDL.Columns[i].Name == "id" {
			col = &statement.DDL.Columns[i]
			break
		}
	}
	if col == nil {
		t.Fatal("expected column id in DDL.Columns")
	}
	if col.GeneratedWhen != "d" {
		t.Fatalf("expected generated_when=d (BY DEFAULT), got %q", col.GeneratedWhen)
	}
	if !col.IsIdentity {
		t.Fatal("expected is_identity=true for identity column")
	}

	// D. Identity options preserved.
	opts := col.IdentityOptions
	if opts == nil {
		t.Fatal("expected identity_options to be populated")
	}
	if opts["start"] != int32(10) {
		t.Fatalf("expected identity_options.start=10, got %v", opts["start"])
	}
	if opts["increment"] != int32(5) {
		t.Fatalf("expected identity_options.increment=5, got %v", opts["increment"])
	}
	if opts["minvalue"] != int32(1) {
		t.Fatalf("expected identity_options.minvalue=1, got %v", opts["minvalue"])
	}
	if opts["maxvalue"] != int32(9999) {
		t.Fatalf("expected identity_options.maxvalue=9999, got %v", opts["maxvalue"])
	}
	if opts["cache"] != int32(20) {
		t.Fatalf("expected identity_options.cache=20, got %v", opts["cache"])
	}
	if opts["cycle"] != true {
		t.Fatalf("expected identity_options.cycle=true, got %v", opts["cycle"])
	}
}

func TestExtractAlterTableAddGeneratedStoredBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement/DDL payload is valid.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}

	// C. Alter payload contains add_column with facts.
	var addAlter *spec.Alter
	for i := range statement.DDL.Alter {
		if statement.DDL.Alter[i].Action == "add_column" && statement.DDL.Alter[i].Name == "full_name" {
			addAlter = &statement.DDL.Alter[i]
			break
		}
	}
	if addAlter == nil {
		t.Fatal("expected add_column alter action for full_name")
	}
	if addAlter.Column == nil || addAlter.Column.Definition == nil {
		t.Fatal("expected alter column definition")
	}
	if addAlter.Column.Definition.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", addAlter.Column.Definition.GeneratedWhen)
	}
	if addAlter.Column.Definition.IsIdentity {
		t.Fatal("expected is_identity=false for generated stored column")
	}
}

func TestExtractAlterTableAddIdentityBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users
	  ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported detail, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement/DDL payload is valid.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected DDL payload")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}

	// C. Alter payload contains add_column with facts.
	var addAlter *spec.Alter
	for i := range statement.DDL.Alter {
		if statement.DDL.Alter[i].Action == "add_column" && statement.DDL.Alter[i].Name == "id" {
			addAlter = &statement.DDL.Alter[i]
			break
		}
	}
	if addAlter == nil {
		t.Fatal("expected add_column alter action for id")
	}
	if addAlter.Column == nil || addAlter.Column.Definition == nil {
		t.Fatal("expected alter column definition")
	}
	if addAlter.Column.Definition.GeneratedWhen != "a" {
		t.Fatalf("expected generated_when=a (ALWAYS), got %q", addAlter.Column.Definition.GeneratedWhen)
	}
	if !addAlter.Column.Definition.IsIdentity {
		t.Fatal("expected is_identity=true for identity column")
	}
}

// --- v0.35.0 Task 1: Characterization tests for state-transition current facts ---

func TestExtractAlterTableDropGeneratedExpressionSupportedFacts(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN full_name DROP EXPRESSION;`

	// A. Confirm now supported.
	statement := extractPostgreSQLStatement(t, sql)
	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}

	// B. Normalized shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected 1 alter item, got %d", len(statement.DDL.Alter))
	}
	if statement.DDL.Alter[0].Action != "drop_expression" {
		t.Fatalf("expected action drop_expression, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.OldName != "full_name" {
		t.Fatalf("expected column.old_name=full_name, got %v", statement.DDL.Alter[0].Column)
	}

	// C. Verify raw AST still carries the facts we need.
	ast := parseAlterTableStmtAST(t, sql)
	cmds := ast.GetCmds()
	if len(cmds) != 1 {
		t.Fatalf("expected 1 AST command, got %d", len(cmds))
	}
	cmd := cmds[0].GetAlterTableCmd()
	if cmd.GetSubtype() != pg_query.AlterTableType_AT_DropExpression {
		t.Fatalf("expected AT_DropExpression, got %s", cmd.GetSubtype().String())
	}
	if cmd.GetName() != "full_name" {
		t.Fatalf("expected column name full_name, got %q", cmd.GetName())
	}
	if cmd.GetDef() != nil {
		t.Fatalf("expected nil def for DROP EXPRESSION, got %T", cmd.GetDef().GetNode())
	}
}

func TestExtractAlterTableSetGeneratedAlwaysSupportedFacts(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS;`

	// A. Confirm now supported.
	statement := extractPostgreSQLStatement(t, sql)
	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}

	// B. Normalized shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected 1 alter item, got %d", len(statement.DDL.Alter))
	}
	if statement.DDL.Alter[0].Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Options == nil || statement.DDL.Alter[0].Options["generated_when"] != "a" {
		t.Fatalf("expected options[generated_when]=a, got %v", statement.DDL.Alter[0].Options)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got %v", statement.DDL.Alter[0].Column)
	}

	// C. Verify raw AST carries transition facts.
	ast := parseAlterTableStmtAST(t, sql)
	cmds := ast.GetCmds()
	cmd := cmds[0].GetAlterTableCmd()
	if cmd.GetSubtype() != pg_query.AlterTableType_AT_SetIdentity {
		t.Fatalf("expected AT_SetIdentity, got %s", cmd.GetSubtype().String())
	}
	if cmd.GetName() != "id" {
		t.Fatalf("expected column name id, got %q", cmd.GetName())
	}

	// The generated mode (ALWAYS=97) is encoded in a DefElem list.
	listNode := cmd.GetDef().GetList()
	if listNode == nil {
		t.Fatal("expected AT_SetIdentity def to be a List")
	}
	items := listNode.GetItems()
	if len(items) != 1 {
		t.Fatalf("expected 1 defelem, got %d", len(items))
	}
	defElem := items[0].GetDefElem()
	if defElem.GetDefname() != "generated" {
		t.Fatalf("expected defname generated, got %q", defElem.GetDefname())
	}
	arg := defElem.GetArg()
	if arg == nil || arg.GetInteger() == nil {
		t.Fatal("expected integer arg for generated setting")
	}
	// PostgreSQL encodes ALWAYS as 97 ('a').
	if arg.GetInteger().GetIval() != 97 {
		t.Fatalf("expected integer 97 for ALWAYS, got %d", arg.GetInteger().GetIval())
	}
}

func TestExtractAlterTableSetGeneratedByDefaultSupportedFacts(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;`

	// A. Confirm now supported.
	statement := extractPostgreSQLStatement(t, sql)
	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}

	// B. Normalized shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected 1 alter item, got %d", len(statement.DDL.Alter))
	}
	if statement.DDL.Alter[0].Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Options == nil || statement.DDL.Alter[0].Options["generated_when"] != "d" {
		t.Fatalf("expected options[generated_when]=d, got %v", statement.DDL.Alter[0].Options)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got %v", statement.DDL.Alter[0].Column)
	}

	// C. Verify raw AST carries transition facts with BY DEFAULT (100 = 'd').
	ast := parseAlterTableStmtAST(t, sql)
	cmds := ast.GetCmds()
	cmd := cmds[0].GetAlterTableCmd()
	if cmd.GetSubtype() != pg_query.AlterTableType_AT_SetIdentity {
		t.Fatalf("expected AT_SetIdentity, got %s", cmd.GetSubtype().String())
	}
	if cmd.GetName() != "id" {
		t.Fatalf("expected column name id, got %q", cmd.GetName())
	}
	listNode := cmd.GetDef().GetList()
	items := listNode.GetItems()
	defElem := items[0].GetDefElem()
	arg := defElem.GetArg()
	// PostgreSQL encodes BY DEFAULT as 100 ('d').
	if arg.GetInteger().GetIval() != 100 {
		t.Fatalf("expected integer 100 for BY DEFAULT, got %d", arg.GetInteger().GetIval())
	}
}

func TestExtractAlterTableDropIdentitySupportedFacts(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id DROP IDENTITY;`

	// A. Confirm now supported.
	statement := extractPostgreSQLStatement(t, sql)
	if statement.Unsupported != nil {
		t.Fatalf("expected supported, got unsupported feature=%q", statement.Unsupported.Feature)
	}

	// B. Normalized shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected 1 alter item, got %d", len(statement.DDL.Alter))
	}
	if statement.DDL.Alter[0].Action != "drop_identity" {
		t.Fatalf("expected action drop_identity, got %q", statement.DDL.Alter[0].Action)
	}
	if statement.DDL.Alter[0].Column == nil || statement.DDL.Alter[0].Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got %v", statement.DDL.Alter[0].Column)
	}

	// C. Verify raw AST carries the facts.
	ast := parseAlterTableStmtAST(t, sql)
	cmds := ast.GetCmds()
	cmd := cmds[0].GetAlterTableCmd()
	if cmd.GetSubtype() != pg_query.AlterTableType_AT_DropIdentity {
		t.Fatalf("expected AT_DropIdentity, got %s", cmd.GetSubtype().String())
	}
	if cmd.GetName() != "id" {
		t.Fatalf("expected column name id, got %q", cmd.GetName())
	}
	if cmd.GetDef() != nil {
		t.Fatalf("expected nil def for DROP IDENTITY, got %T", cmd.GetDef().GetNode())
	}
}

// --- Task 2: Supported state-transition tests (red -> green) ---

func TestExtractAlterTableDropGeneratedExpressionBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN full_name DROP EXPRESSION;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter item")
	}

	// C. Explicit transition modeling.
	alter := statement.DDL.Alter[0]
	if alter.Action != "drop_expression" {
		t.Fatalf("expected action drop_expression, got %q", alter.Action)
	}
	if alter.Column == nil || alter.Column.OldName != "full_name" {
		t.Fatalf("expected column.old_name=full_name, got column=%v", alter.Column)
	}
}

func TestExtractAlterTableSetGeneratedAlwaysBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter item")
	}

	// C. Explicit transition modeling.
	alter := statement.DDL.Alter[0]
	if alter.Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %q", alter.Action)
	}
	if alter.Options == nil || alter.Options["generated_when"] != "a" {
		t.Fatalf("expected options[generated_when]=a, got %v", alter.Options)
	}
	if alter.Column == nil || alter.Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got column=%v", alter.Column)
	}
}

func TestExtractAlterTableSetGeneratedByDefaultBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter item")
	}

	// C. Explicit transition modeling.
	alter := statement.DDL.Alter[0]
	if alter.Action != "set_generated" {
		t.Fatalf("expected action set_generated, got %q", alter.Action)
	}
	if alter.Options == nil || alter.Options["generated_when"] != "d" {
		t.Fatalf("expected options[generated_when]=d, got %v", alter.Options)
	}
	if alter.Column == nil || alter.Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got column=%v", alter.Column)
	}
}

func TestExtractAlterTableDropIdentityBecomesSupported(t *testing.T) {
	t.Parallel()
	sql := `ALTER TABLE users ALTER COLUMN id DROP IDENTITY;`

	statement := extractPostgreSQLStatement(t, sql)

	// A. No unsupported.
	if statement.Unsupported != nil {
		t.Fatalf("expected no unsupported, got feature=%q reason=%q", statement.Unsupported.Feature, statement.Unsupported.Reason)
	}

	// B. Statement shape.
	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind ddl, got %q", statement.Kind)
	}
	if statement.DDL == nil {
		t.Fatal("expected non-nil DDL")
	}
	if statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected operation alter_table, got %q", statement.DDL.Operation)
	}
	if len(statement.DDL.Alter) == 0 {
		t.Fatal("expected at least one alter item")
	}

	// C. Explicit transition modeling.
	alter := statement.DDL.Alter[0]
	if alter.Action != "drop_identity" {
		t.Fatalf("expected action drop_identity, got %q", alter.Action)
	}
	if alter.Column == nil || alter.Column.OldName != "id" {
		t.Fatalf("expected column.old_name=id, got column=%v", alter.Column)
	}
}

// ---------------------------------------------------------------------------
// v0.37.0 Task 1: PostgreSQL primary-key AST and contract characterization
// ---------------------------------------------------------------------------

// --- AST-level characterization: prove CONSTR_PRIMARY is stable and readable ---
