//go:build postgresql

package postgresql

import (
	"strings"
	"testing"

	"github.com/Fanduzi/DeltaScope/internal/domain/spec"
)

func TestParseAlterTableSetExpressionNormalizesBoundedMetadata(t *testing.T) {
	t.Parallel()

	const sql = "ALTER TABLE users ALTER COLUMN full_name SET EXPRESSION AS (first_name || ' ' || last_name)"

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table ddl payload, got %#v", statement.DDL)
	}
	if statement.DDL.Table == nil || statement.DDL.Table.Name != "users" {
		t.Fatalf("expected table name users, got %#v", statement.DDL.Table)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported statement, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected one alter action, got %d", len(statement.DDL.Alter))
	}

	alter := statement.DDL.Alter[0]
	if alter.Action != "set_expression" {
		t.Fatalf("expected action set_expression, got %q", alter.Action)
	}
	if alter.Name != "full_name" {
		t.Fatalf("expected name full_name, got %q", alter.Name)
	}

	assertOption(t, alter.Options, "column", "full_name")
	assertOption(t, alter.Options, "has_expression", "true")

	forbidden := []string{"first_name", "last_name", "||", "raw_sql", "expression"}
	assertOptionsForbidden(t, alter.Options, forbidden)
}

func TestParseAlterTableAddIdentityNormalizesBoundedMetadata(t *testing.T) {
	t.Parallel()

	const sql = "ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table ddl payload, got %#v", statement.DDL)
	}
	if statement.DDL.Table == nil || statement.DDL.Table.Name != "users" {
		t.Fatalf("expected table name users, got %#v", statement.DDL.Table)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported statement, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected one alter action, got %d", len(statement.DDL.Alter))
	}

	alter := statement.DDL.Alter[0]
	if alter.Action != "add_identity" {
		t.Fatalf("expected action add_identity, got %q", alter.Action)
	}
	if alter.Name != "id" {
		t.Fatalf("expected name id, got %q", alter.Name)
	}

	assertOption(t, alter.Options, "column", "id")
	assertOption(t, alter.Options, "identity", "true")
	assertOption(t, alter.Options, "generated_when", "by_default")

	forbidden := []string{"sequence_options", "start", "increment", "cache", "cycle", "raw_sql"}
	assertOptionsForbidden(t, alter.Options, forbidden)
}

func TestParseAlterTableAddExclusionConstraintNormalizesBoundedMetadata(t *testing.T) {
	t.Parallel()

	const sql = "ALTER TABLE bookings ADD CONSTRAINT bookings_no_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&)"

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table ddl payload, got %#v", statement.DDL)
	}
	if statement.DDL.Table == nil || statement.DDL.Table.Name != "bookings" {
		t.Fatalf("expected table name bookings, got %#v", statement.DDL.Table)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported statement, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected one alter action, got %d", len(statement.DDL.Alter))
	}

	alter := statement.DDL.Alter[0]
	if alter.Action != "add_exclusion_constraint" {
		t.Fatalf("expected action add_exclusion_constraint, got %q", alter.Action)
	}
	if alter.Name != "bookings_no_overlap" {
		t.Fatalf("expected name bookings_no_overlap, got %q", alter.Name)
	}

	assertOption(t, alter.Options, "constraint", "bookings_no_overlap")
	assertOption(t, alter.Options, "constraint_type", "exclusion")
	assertOption(t, alter.Options, "access_method", "gist")

	forbidden := []string{
		"exclusions", "operator", "operator_class",
		"room_id", "during", "&&",
		"predicate", "where_clause", "raw_sql",
	}
	assertOptionsForbidden(t, alter.Options, forbidden)
}

func TestParseAlterTableMoveAllTablespaceNormalizesBoundedMetadata(t *testing.T) {
	t.Parallel()

	const sql = "ALTER TABLE ALL IN TABLESPACE pg_default SET TABLESPACE fastspace"

	statement := extractPostgreSQLStatement(t, sql)

	if statement.Kind != spec.KindDDL {
		t.Fatalf("expected kind DDL, got %q", statement.Kind)
	}
	if statement.DDL == nil || statement.DDL.Operation != spec.DDLOperationAlterTable {
		t.Fatalf("expected alter_table ddl payload, got %#v", statement.DDL)
	}
	if statement.DDL.Table != nil {
		t.Fatalf("expected nil table (ALL IN TABLESPACE has no single-table identity), got %#v", statement.DDL.Table)
	}
	if statement.Unsupported != nil {
		t.Fatalf("expected supported statement, got unsupported %#v", statement.Unsupported)
	}
	if len(statement.DDL.Alter) != 1 {
		t.Fatalf("expected one alter action, got %d", len(statement.DDL.Alter))
	}

	alter := statement.DDL.Alter[0]
	if alter.Action != "move_all_tablespace" {
		t.Fatalf("expected action move_all_tablespace, got %q", alter.Action)
	}

	assertOption(t, alter.Options, "object_type", "table")
	assertOption(t, alter.Options, "source_tablespace", "pg_default")
	assertOption(t, alter.Options, "target_tablespace", "fastspace")
	assertOption(t, alter.Options, "has_table_identity", "false")
}

// assertOption checks that options[key] == value.
func assertOption(t *testing.T, options map[string]string, key, value string) {
	t.Helper()
	if options == nil {
		t.Fatalf("options is nil, expected key %q", key)
	}
	got, ok := options[key]
	if !ok {
		t.Fatalf("options missing key %q, have keys: %v", key, optionsKeys(options))
	}
	if got != value {
		t.Fatalf("options[%q] = %q, want %q", key, got, value)
	}
}

// assertOptionsForbidden checks that none of the forbidden strings appear as
// options keys or in options values.
func assertOptionsForbidden(t *testing.T, options map[string]string, forbidden []string) {
	t.Helper()
	for _, f := range forbidden {
		for k, v := range options {
			if strings.EqualFold(k, f) {
				t.Errorf("forbidden key %q found in options", f)
			}
			if strings.Contains(strings.ToLower(v), strings.ToLower(f)) {
				t.Errorf("forbidden value %q found in options[%q]=%q", f, k, v)
			}
		}
	}
}

// optionsKeys returns sorted option keys for error messages.
func optionsKeys(options map[string]string) []string {
	keys := make([]string, 0, len(options))
	for k := range options {
		keys = append(keys, k)
	}
	return keys
}
