#!/usr/bin/env bash
# input: release version and darwin archive sha256 values for amd64 and arm64 main assets
# output: rendered Homebrew Cask content for the deltascope tap
# pos: deterministic cask rendering helper for native darwin PG-capable release convergence

set -euo pipefail

VERSION="${VERSION:-}"
DARWIN_AMD64_SHA256="${DARWIN_AMD64_SHA256:-}"
DARWIN_ARM64_SHA256="${DARWIN_ARM64_SHA256:-}"

fail() {
  printf '[render-homebrew-cask][FAIL] %s\n' "$*" >&2
  exit 1
}

[[ -n "${VERSION}" ]] || fail "VERSION is required"
[[ -n "${DARWIN_AMD64_SHA256}" ]] || fail "DARWIN_AMD64_SHA256 is required"
[[ -n "${DARWIN_ARM64_SHA256}" ]] || fail "DARWIN_ARM64_SHA256 is required"

cat <<EOF
# This file was generated by DeltaScope release automation. DO NOT EDIT.
cask "deltascope" do
  version "${VERSION#v}"

  on_macos do
    on_intel do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64_SHA256}"
    end
    on_arm do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64_SHA256}"
    end
  end

  name "deltascope"
  desc "Offline SQL review for MySQL, TiDB, and PostgreSQL"
  homepage "https://github.com/Fanduzi/DeltaScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deltascope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deltascope"]
    end
  end
end
EOF
